antvis/G

index.js
package.json

exprots common util

---

src/core/mixin/transform.js

fix(transform): when inner matrix is null, cancel transform in invert()

---

package.json
src/core/shape.js
src/shape/arc.js
src/shape/circle.js
src/shape/cubic.js
src/shape/ellipse.js
src/shape/fan.js
src/shape/line.js
src/shape/marker.js
src/shape/path.js
src/shape/polygon.js
src/shape/polyline.js
src/shape/quadratic.js
src/shape/rect.js
src/shape/text.js
test/unit/shape/marker-spec.js

Hit append

---

package.json
src/core/element.js
src/core/mixin/animate.js
test/unit/core/animate-spec.js

1. 增加 stopAnimate 方法
2. shape destroy 时，中断动画

feat(animate): add stop animate

---

package.json

Here is the warning message from GitHub:
We found potential security vulnerabilities in your dependencies.
Some of the dependencies defined in your package.json have known security vulnerabilities and should be updated.
Review vulnerable dependencies
Only users who have been granted access to vulnerability alerts for this repository can see this message.
Learn more about vulnerability alerts

chore(dev): update vulnerable jquery

---

package.json
src/core/mixin/animate.js
test/unit/core/animate-spec.js
test/unit/core/clip-spec.js
test/unit/core/group-spec.js
test/unit/shape/arc-spec.js
test/unit/shape/circle-spec.js
test/unit/shape/cubic-spec.js
test/unit/shape/ellipse-spec.js
test/unit/shape/fan-spec.js
test/unit/shape/image-spec.js
test/unit/shape/line-spec.js
test/unit/shape/marker-spec.js
test/unit/shape/math-arc-spec.js
test/unit/shape/path-spec.js
test/unit/shape/polygon-spec.js
test/unit/shape/polyline-spec.js
test/unit/shape/quadratic-spec.js
test/unit/shape/rect-spec.js
test/unit/shape/text-spec.js
test/unit/util/path-spec.js

* 添加 animate repeat 特性
* 改进测试用例的一些写法

Add animate repeat

---

package.json
src/core/mixin/animate.js
test/unit/core/animate-spec.js

fix(animate): fixed bug of animate

---

src/shape/line.js
src/shape/text.js
src/shape/util/arrow.js
test/unit/shape/line-spec.js
test/unit/shape/text-spec.js

- Text新增outline特性
- Arrow支持用Marker定义形状，保持默认箭头不变

Add new features

---

package.json
src/shape/text.js
test/unit/shape/text-spec.js

去除outline接口，直接使用stroke,fill即可满足#28

2.0.7-beta.5

---

package.json
src/core/shape.js
src/shape/arc.js
src/shape/cubic.js
src/shape/line.js
src/shape/path.js
src/shape/polyline.js
src/shape/quadratic.js
src/shape/util/arrow.js
src/shape/util/path-segment.js
test/unit/core/element-spec.js
test/unit/shape/cubic-spec.js
test/unit/shape/line-spec.js
test/unit/shape/path-spec.js
test/unit/util/path-spec.js

- 修复自定义箭头显示问题
- 修复path曲线的箭头朝向问题
- 修改自定义箭头接口
```
startArrow/endArrow: new Marker(...)
```

Fix path arrow

---

package.json
src/canvas/canvas.js
src/canvas/core/element.js
src/canvas/core/group.js
src/canvas/shape/circle.js
src/index.js
src/svg/canvas.js
src/svg/core/element.js
src/svg/core/group.js
src/util/mixin/animation.js
src/util/mixin/timeline.js
test/unit/canvas/core/animate-spec.js
test/unit/svg/core/animate-spec.js

- 动画多timer -> 单timer
- 支持暂停/恢复动画
- 支持同属性动画叠加

Animation refactor

---

package.json
src/index.js
src/util/mixin/animation.js
src/util/mixin/timeline.js
test/unit/canvas/core/animate-spec.js
test/unit/svg/core/animate-spec.js

Fix animate props

---

package.json
src/index.js
src/util/mixin/animation.js
test/unit/canvas/core/animate-spec.js

Fix animation

---

package.json
src/util/common.js
src/util/matrix.js
test/unit/canvas/core/element-spec.js
test/unit/svg/core/element-spec.js

chore(dev): require entries from src to lib

---

package.json
src/core/mixin/timeline.js
src/index.js
src/renderers/svg/getShape.js
test/unit/canvas/core/animate-spec.js
test/unit/svg/core/animate-spec.js

- 添加timeline层次的停止动画
- 修正dom事件捕获

Add stop aniations

---

package.json
src/canvas.js
src/core/mixin/isPointInPath.js
src/index.js
src/renderers/svg/painter.js
src/shapes/rect.js
src/util/format.js
test/unit/canvas/canvas-spec.js
test/unit/svg/canvas-spec.js

- 修复svg的`visible`异常
- 修复`toFront`异常
- 修复`getClientByPoint`异常

Fix visibility

---

package.json
src/canvas.js
src/index.js
src/renderers/svg/painter.js
test/unit/canvas/canvas-spec.js
test/unit/svg/canvas-spec.js

Fix 3.1.0 beta

---

package.json
src/renderers/svg/painter.js
src/util/common.js
src/util/path.js

Fix path issues

---

src/renderers/canvas/util.js
src/util/format.js

fix(remove):remove useless function

---

package.json
src/canvas.js
src/index.js
src/renderers/svg/painter.js
test/bugs/issue-svg-spec.js
test/bugs/issue-svg.js
test/unit/canvas/canvas-spec.js
test/unit/svg/canvas-spec.js

- 新增方法获取当前renderer类型
- 修复svg z-index问题
- 修复svg渲染效率问题

Fix svg efficiency

---

src/core/mixin/event.js

解决节点有时点击不上的问题

---

package.json
src/renderers/svg/painter.ts

fix(svg): baseline should be compatible with FireFox browser

---

packages/g-base/README.md
packages/g-base/__tests__/unit/element-spec.js
packages/g-base/__tests__/unit/group-spec.js
packages/g-base/__tests__/unit/shape-spec.js
packages/g-base/package.json
packages/g-base/src/abstract/canvas.ts
packages/g-base/src/abstract/container.ts
packages/g-base/src/abstract/element.ts
packages/g-base/src/abstract/group.ts
packages/g-base/src/abstract/shape.ts
packages/g-base/src/interfaces.ts
packages/g-base/src/types.ts
packages/g-base/src/util/matrix.ts
packages/g-canvas/__tests__/unit/canvas-draw-spec.js
packages/g-canvas/__tests__/unit/canvas-spec.js
packages/g-canvas/src/canvas.ts
packages/g-canvas/src/group.ts
packages/g-canvas/src/interfaces.ts
packages/g-canvas/src/shape/base.ts
packages/g-canvas/src/shape/image.ts
packages/g-canvas/src/shape/marker.ts
packages/g-canvas/src/shape/path.ts
packages/g-canvas/src/shape/text.ts
packages/g-canvas/src/types.ts
packages/g-canvas/src/util/draw.ts
packages/g-canvas/src/util/util.ts

这次改动比较大：
* 支持了 getTotalMatrix，getCanvasBBox
* 支持画布的局部刷新、延迟刷新、自动刷新
* 矩阵计算在 g-base 中实现
* 修复了 changeSize 时的 bug

feat(draw): support local refresh

---

packages/g-svg/src/defs/arrow.ts
packages/g-svg/src/defs/clip.ts
packages/g-svg/src/defs/gradient.ts
packages/g-svg/src/defs/index.ts
packages/g-svg/src/defs/pattern.ts
packages/g-svg/src/defs/shadow.ts

feat(svg): add defs

---

packages/g-svg/__tests__/unit/shape/rect-spec.js
packages/g-svg/src/shape/rect.ts
packages/g-svg/src/util/format.ts

feat(svg): add rect shape

---

packages/g-svg/__tests__/unit/shape/circle-spec.js
packages/g-svg/src/shape/circle.ts

feat(svg): add circle shape

---

packages/g-svg/__tests__/unit/shape/ellipse-spec.js
packages/g-svg/src/shape/ellipse.ts

feat(svg): add ellipse shape

---

packages/g-svg/__tests__/unit/shape/line-spec.js
packages/g-svg/src/shape/line.ts

feat(svg): add line shape

---

packages/g-svg/__tests__/unit/shape/path-spec.js
packages/g-svg/src/shape/path.ts

feat(svg): add path shape

---

packages/g-svg/__tests__/unit/shape/text-spec.js
packages/g-svg/src/shape/text.ts

feat(svg): add text shape

---

packages/g-svg/__tests__/unit/shape/polyline-spec.js
packages/g-svg/src/shape/polyline.ts

feat(svg): add polyline shape

---

packages/g-svg/__tests__/unit/shape/polygon-spec.js
packages/g-svg/src/shape/polygon.ts

feat(svg): add polygon shape

---

packages/g-svg/__tests__/unit/shape/marker-spec.js
packages/g-svg/src/shape/marker/index.ts
packages/g-svg/src/shape/marker/symbols.ts

feat(svg): add marker shape

---

packages/g-svg/__tests__/unit/shape/dom-spec.js
packages/g-svg/src/shape/dom.ts

feat(svg): add dom shape

---

packages/g-base/__tests__/bugs/issue-162-spec.js
packages/g-base/__tests__/mocha.opts
packages/g-base/src/util/container.ts

fix(element): should set canvas for element recursively

---

.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/----please-use-antv-issue-helper---.md
.github/PULL_REQUEST_TEMPLATE.md
ISSUE_TEMPLATE.md

chore: update issue and pull request template

---

packages/g-base/__tests__/unit/element-spec.js
packages/g-base/__tests__/unit/group-spec.js
packages/g-base/__tests__/unit/index.spec.js
packages/g-base/__tests__/unit/shape-spec.js
packages/g-base/src/abstract/container.ts
packages/g-base/src/abstract/element.ts
packages/g-base/src/abstract/group.ts
packages/g-base/src/abstract/shape.ts
packages/g-base/src/bbox.ts
packages/g-base/src/index.ts
packages/g-base/src/interfaces.ts
packages/g-base/src/types.ts
packages/g-canvas/__tests__/unit/index-spec.js
packages/g-canvas/__tests__/unit/shape/circle-spec.js
packages/g-canvas/__tests__/unit/shape/path-spec.js
packages/g-canvas/src/index.ts
packages/g-canvas/src/shape/base.ts
packages/g-svg/__tests__/unit/index-spec.js
packages/g-svg/src/index.ts
packages/g-svg/src/shape/base.ts

- Use `BBox class` to replace simple `BBox type`.
- close #175.

feat(g-base): add BBox class

---

packages/g-base/__tests__/unit/animate-spec.js
packages/g-base/package.json
packages/g-base/src/abstract/canvas.ts
packages/g-base/src/abstract/element.ts
packages/g-base/src/animate/timeline.ts
packages/g-base/src/interfaces.ts
packages/g-base/src/types.ts
packages/g-base/src/util/container.ts
packages/g-base/src/util/path.ts
tslint.json

- 4.0 的[动画方案](https://www.yuque.com/antv/ou292n/uvu7rx#pSvVf)实现，`Element` 上实现了如下接口:
```js
duration: 动画执行时间
easing: 动画缓动效果
delay: 动画执行的延迟时间
repeat: 动画是否重复
callback: 动画执行完时的回调
pauseCallback: 动画暂停时的回调函数
resumeCallback: 动画重新唤醒时的回调函数
```

feat(g-base): animate

---

lerna.json
packages/g-base/package.json
packages/g-canvas/package.json
packages/g-math/package.json
packages/g-mobile/package.json
packages/g-svg/package.json
packages/g-webgl/package.json

- None.
- 修改 `lerna` 的发版模式为 `independent`；
- `@antv/g-mobile` 和 `@antv/g-webgl` 暂不发布，需要设为私有:
```json
"private": true
```
- 带有 `scope` 的包，需要在 `package.json` 中配置:
```json
"publishConfig": {
"access": "public"
}
```
- `@antv/g-base` 和 `@antv/g-math` 新增 `ES Module` 打包，方便做 `tree-shaking`；

fix(version): use correct version for publish

---

lerna.json

- 由于 `lerna publish` 的 `commit` 格式不符合 [@commitlint/config-angular](https://github.com/conventional-changelog/commitlint/tree/master/@commitlint/config-angular) 的要求，导致发版时报错。因此设置:
```json
"publish": {
"commitHooks": false
}
```

fix(lerna): skip commit hooks to avoid failure when lerna publish

---

package.json
packages/g-base/package.json
packages/g-canvas/package.json
packages/g-math/package.json
packages/g-mobile/package.json
packages/g-svg/package.json
packages/g-webgl/package.json

- Installation failed for unnecessary `postinstall` script command:
| 🇺🇸 English | 🐞 Fix installation failure by removing unnecessary `postinstall script`.  |
| 🇨🇳 Chinese | 🐞 修复安装时错误，去掉不必要的 `postinstall` 脚本命令。 |

fix(build): remove postinstall script

---

packages/g-base/src/abstract/container.ts
packages/g-base/src/abstract/shape.ts
packages/g-canvas/__tests__/bugs/issue-202-spec.js

- Close #202.
- Should use the new value returned by `invertFromMatrix`.
| 🇺🇸 English | 🐞 [g-base] Fix incorrect hit for shape with matrix. #202 |
| 🇨🇳 Chinese | 🐞 [g-base] 修复设置了 `matrix` 的图形拾取不正确的问题。#202          |

fix(g-base): invertFromMatrix should be effective

---

packages/g-base/src/types.ts
packages/g-base/src/util/path.ts

feat: add path array type define

---

packages/g-base/src/event/event-contoller.ts
packages/g-canvas/tests/bugs/issue-227-spec.js
packages/g-canvas/tests/util.ts

- Close #227.
| 🇺🇸 English | 🐞 [g-base] Fix that event delegation on shape is not effective. #227 |
| 🇨🇳 Chinese | 🐞 [g-base] 修复图形上的事件代理不生效的问题。#227 |

fix(g-base): event delegation on shape should be effective

---

package.json
site/locale.json
site/pages/index.zh.tsx

docs: upgrade @antv/gatsby-theme-antv to 0.5.0

---

packages/g-canvas/src/shape/marker.ts
packages/g-canvas/tests/bugs/issue-236-spec.js

- Close #236.
| 🇺🇸 English | 🐞 [g-canvas] Fix that animation for marker is not effective. #236  |
| 🇨🇳 Chinese | 🐞 [g-canvas] 修复 `marker` 动画不生效的问题。#236          |

fix(g-canvas): animation for marker should be effective

---

packages/g-canvas/src/shape/path.ts
packages/g-canvas/src/util/path.ts
packages/g-canvas/tests/bugs/issue-232-spec.js

- Close #232.
| 🇺🇸 English | 🐞 [g-canvas] Fix that bbox calculation is not correct for path with angle. #232.          |
| 🇨🇳 Chinese | 🐞 [g-canvas] 修复带有夹角 `path` 的包围盒计算不正确的问题。#232.        |

fix(g-canvas): bbox calculation should be correct for path with angle

---

gatsby-config.js
package.json

close https://github.com/antvis/gatsby-theme-antv/issues/6

chore: upgrade theme

---

packages/g-base/src/event/event-contoller.ts
packages/g-canvas/tests/bugs/issue-233-spec.js

- Close #233.
- There are three situations when cursor style needs to be changed:
| 🇺🇸 English | 🐞 [g-base] Fix that cursor attr for shape is not effective. #233.          |
| 🇨🇳 Chinese | 🐞 [g-base] 修复图形的 cursor 属性不生效的问题。#233.          |

fix(g-base): cursor attr for shape should be effective

---

.gitignore
src/core/mixin/animation.js
src/core/mixin/timeline.js
src/util/index.js
test/unit/canvas/core/animate-spec.js
test/unit/canvas/core/event-spec.js

1. Fix 渐变色动画，虽无补间，但是颜色需要更新。
2. drag 单测修改，无相关代码修改

Fix 渐变色动画，虽无补间，但是颜色需要更新。

---

packages/g-base/src/abstract/base.ts
packages/g-base/src/event/event-contoller.ts
packages/g-base/src/event/graph-event.ts
packages/g-base/tests/unit/event-spec.js
packages/g-canvas/tests/bugs/issue-249-spec.js

- Close #249.
- 事件对象上新增 `name` 属性，用于获取事件名称，其中 `*` 事件对应的事件名称是动态的。给出以下示例进行说明:
```js
shape.on('click', (ev) => {
expect(ev.name).eqls('click');
});
```
```js
shape.on('*', (ev) => {
expect(ev.name).eqls('触发的事件类型');
});
```
```js
group.on('click', (ev) => {
expect(ev.name).eqls('click');
});
```
```js
group.on('shape:click', (ev) => {
expect(ev.name).eqls('shape:click');
});
```
```js
group.on('*', (ev) => {
expect(ev.name).eqls('触发的(委托)事件类型');
});
```
| 🇺🇸 English | 🌟 [g-base] support `*` for event delegation and add `name` attr for event. #249         |
| 🇨🇳 Chinese | 🌟 [g-base] 事件委托支持 `*` 通配符匹配，以及事件新增 `name` 和 `delegateObject` 属性。#249          |

feat(g-base): support * for event delegation, add name and delegateObject for event

---

README-zh_CN.md
docs/guide/introduce.en.md
docs/guide/introduce.zh.md
packages/g-canvas/README-zh_CN.md
packages/g-svg/README-zh_CN.md

docs: add README

---

docs/api/group.en.md
docs/api/group.zh.md
packages/g-base/src/abstract/group.ts
packages/g-base/src/interfaces.ts
packages/g-base/tests/unit/group-spec.js

- Close #301.
| 🇺🇸 English | 🌟[g-base] Add `findAllByName` function for Group. #301          |
| 🇨🇳 Chinese | 🌟[g-base] Group 上新增成员函数 `findAllByName`。#301          |

feat(g-base): add findAllByName function for Group

---

src/shapes/marker.js
test/bugs/issue-305-spec.js

- Close #305.
| 🇺🇸 English | 🐞 [canvas] Fix Marker not compatiable with `r` attr. #305          |
| 🇨🇳 Chinese | 🐞 [canvas] 修复 Marker 不兼容 `r` 绘图属性的问题。#305          |

fix(canvas): marker should be compatiable with r attr

---

docs/api/shape/path.en.md
docs/api/shape/path.zh.md
examples/animation/onFrame/demo/along-path.js
examples/animation/onFrame/demo/meta.json
packages/g-canvas/src/shape/path.ts
packages/g-canvas/tests/unit/shape/path-spec.js
packages/g-svg/src/shape/path.ts
packages/g-svg/tests/unit/shape/path-spec.js

- Ref #295.
| 🇺🇸 English | 🌟 [g-canvas & g-svg] Add `getPoint(ratio)` method for Path. #295         |
| 🇨🇳 Chinese | 🌟 [g-canvas & g-svg] Path 上新增 `getPoint(ratio)` 成员方法。#295          |

feat(g-canvas & g-svg): add getPoint method for Path

---

.eslintignore
.gitignore
docs/api/canvas.en.md
docs/api/canvas.zh.md
packages/g-base/src/abstract/canvas.ts
packages/g-base/src/interfaces.ts
packages/g-base/src/types.ts
packages/g-canvas/src/canvas.ts
packages/g-canvas/tests/unit/canvas-spec.js
packages/g-svg/src/canvas.ts
packages/g-svg/tests/unit/canvas-spec.js

- Close #302.
| 🇺🇸 English | 🌟 [g-base] Add `getRenderer()` method for Canvas to get current rendering engine. #302          |
| 🇨🇳 Chinese | 🌟 [g-base] Canvas 新增 `getRenderer()` 成员方法属性，用来获取当前的渲染引擎。#302           |

feat(g-base): add getRenderer method for canvas

---

examples/animation/attribute/demo/multiple-attributes.js
examples/animation/attribute/demo/single-attribute.js
examples/animation/onFrame/demo/basic.js
examples/animation/onFrame/demo/concurrent.js
examples/animation/onFrame/demo/rotate.js
examples/animation/path/demo/along-circle.js
examples/animation/path/demo/along-line.js
examples/animation/path/demo/along-path.js
examples/animation/path/demo/along-polyline.js
examples/animation/path/demo/along-rect.js
examples/event/bubble/demo/basic.js
examples/event/delegate/demo/basic.js
examples/event/shape/demo/basic.js
examples/shape/circle/demo/basic.js
examples/shape/dom/demo/basic.js
examples/shape/ellipse/demo/basic.js
examples/shape/image/demo/basic.js
examples/shape/line/demo/basic.js
examples/shape/marker/demo/basic.js
examples/shape/path/demo/basic.js
examples/shape/polygon/demo/basic.js
examples/shape/polyline/demo/basic.js
examples/shape/rect/demo/basic.js
examples/shape/text/demo/basic.js
gatsby-browser.js

- Ref: https://github.com/antvis/gatsby-theme-antv/issues/80
- 修改 demo 代码中的 G 引入方式，以修复跳转到外部的 CodeSandBox 和 StackBlitz 打开时无法正常运行的问题。
| 🇺🇸 English | -          |
| 🇨🇳 Chinese |  -          |

docs(demo): modify the import of G

---

docs/api/canvas.en.md
docs/api/canvas.zh.md
packages/g-base/src/abstract/canvas.ts
packages/g-base/src/event/event-contoller.ts
packages/g-base/src/interfaces.ts
packages/g-base/src/types.ts
packages/g-canvas/tests/bugs/issue-319-spec.js

- Close #319.
| 🇺🇸 English | 🌟[g-base] Add `getCursor()` and `setCursor(cursor)` method for Canvas to get and set cursor style of canvas. #319          |
| 🇨🇳 Chinese | 🌟[g-base] Canvas 上新增 `getCursor()` and `setCursor(cursor)` 方法，用于获取和设置画布的 `cursor` 样式。#319          |

feat(g-base): add getCursor() and setCursor(cursor) method for Canvas

---

docs/api/canvas.zh.md
docs/api/general/container.en.md
docs/api/general/container.zh.md
docs/api/general/element.en.md
docs/api/general/element.zh.md
docs/api/group.en.md
docs/api/group.zh.md
docs/api/shape/api.en.md
docs/api/shape/api.zh.md
docs/api/shape/circle.en.md
docs/api/shape/ellipse.en.md
docs/api/shape/rect.en.md
gatsby-config.js
packages/g-base/src/abstract/container.ts
packages/g-base/src/abstract/group.ts
packages/g-base/src/interfaces.ts

- 将 Group 中一些工具方法移动到 Container 中，方便 Group 和 Canvas 都能复用。
| 🇺🇸 English | 🌟 [g-base] Move util methods of Group to Container for better reuse of Canvas.          |
| 🇨🇳 Chinese | 🌟 [g-base] 将 Group 中的工具方法抽离到 Container 中去，方便 Canvas 复用。         |

feat(g-base): move util methods of Group to Container for better reuse of Canvas

---

packages/g-base/package.json
packages/g-base/src/animate/timeline.ts
packages/g-canvas/src/canvas.ts
packages/g-canvas/src/group.ts
packages/g-canvas/src/shape/base.ts
packages/g-canvas/src/util/draw.ts
packages/g-canvas/tests/bugs/issue-323-spec.js

- Close #323.
| 🇺🇸 English | 🐞 [g-canvas] Fix `matrix` animation for `clip` not working. #323        |
| 🇨🇳 Chinese | 🐞 [g-canvas] 修复 `clip` 的矩阵动画不生效的问题。#323          |

fix(g-canvas): matrix animation for clip should work

---

packages/g-base/src/index.ts
packages/g-canvas/src/index.ts
packages/g-svg/src/index.ts

把上层可能用到的interface在index中re-export出来，方便上层使用

feat: export interface to user

---

package.json
src/core/mixin/event.js
src/index.js
test/unit/canvas/core/event-spec.js

- 之前有一部分 3.x 的代码是在内网开发并发版，需要合并回 github 的仓库。

chore: Merge code from datavis/g-3.x

---

packages/g-canvas/src/canvas.ts
packages/g-canvas/src/interfaces.ts
packages/g-canvas/tests/bugs/issue-350-spec.js

- Close #350.
| 🇺🇸 English | 🐞 [g-canvas] Fix that `matrix` attr for `canvas` works incorrectly. #350          |
| 🇨🇳 Chinese | 🐞 [g-canvas] 修复 `canvas` 上的 `matrix` 属性导致渲染不正确的问题。#350          |

fix(g-canvas): matrix attr for canvas should work correctly

---

packages/g-canvas/src/shape/polyline.ts
packages/g-canvas/src/util/arrow.ts
packages/g-canvas/tests/unit/shape/polyline-spec.js

| 🇺🇸 English | 🌟 [g-canvas] Support `arrow` for Polyline.          |
| 🇨🇳 Chinese | 🌟 [g-canvas] Polyline 支持设置箭头。         |

feat(g-canvas): support arrow for Polyline

---

packages/g-canvas/src/shape/marker.ts
packages/g-canvas/src/shape/path.ts
packages/g-canvas/src/util/arrow.ts
packages/g-canvas/src/util/draw.ts
packages/g-canvas/tests/unit/shape/path-spec.js

| 🇺🇸 English | 🌟 [g-canvas] Support `arrow` for Path.          |
| 🇨🇳 Chinese | 🌟 [g-canvas] Path 支持设置箭头。         |

feat(g-canvas): support arrow for Path

---

packages/g-canvas/src/shape/circle.ts
packages/g-canvas/src/shape/ellipse.ts
packages/g-canvas/src/shape/image.ts
packages/g-canvas/src/shape/line.ts
packages/g-canvas/src/shape/rect.ts
packages/g-canvas/src/shape/text.ts
packages/g-canvas/tests/unit/shape/image-spec.js
packages/g-svg/src/shape/circle.ts
packages/g-svg/src/shape/ellipse.ts
packages/g-svg/src/shape/image.ts
packages/g-svg/src/shape/line.ts
packages/g-svg/src/shape/path.ts
packages/g-svg/src/shape/polyline.ts
packages/g-svg/src/shape/rect.ts
packages/g-svg/src/shape/text.ts

chore(g-canvas & g-svg): give default value for some attrs for shape

---

packages/g-canvas/src/util/util.ts

- Close #354
| 🇺🇸 English | 🐞 Fix `mergeRegion` function work incorrectly. #354         |
| 🇨🇳 Chinese | 🐞 修复 `mergeRegion` 函数计算结果不正确的问题。#354          |

fix(g-canvas): mergeRegion util function should work correctly

---

packages/g-base/src/animate/timeline.ts
packages/g-svg/src/canvas.ts
packages/g-svg/src/defs/clip.ts
packages/g-svg/src/group.ts
packages/g-svg/src/interfaces.ts
packages/g-svg/src/shape/base.ts
packages/g-svg/src/shape/rect.ts
packages/g-svg/src/util/dom.ts
packages/g-svg/src/util/draw.ts
packages/g-svg/tests/bugs/issue-359-spec.js

- Close #359.
| 🇺🇸 English | 🐞 [g-svg] Fix that `clip` animation doesn't work. #359          |
| 🇨🇳 Chinese | 🐞 [g-svg] 修复 `clip` 动画不生效的问题。#359          |

fix(g-svg): clip animation should work

---

packages/g-base/package.json
packages/g-base/src/event/event-contoller.ts
packages/g-base/tests/unit/event-spec.js

- Ref #344;
| 🇺🇸 English | 🌟 [g-base] Canvas supports `drag`、`dragstart` and `dragend` event. #344          |
| 🇨🇳 Chinese | 🌟 [g-base] Canvas 支持 `drag`、`dragstart` 和 `dragend` 事件。#344          |
* 支持 canvas 的 dragstart, drag 和 dragend 事件

feat(drag): support canvas drag

---

packages/g-canvas/src/shape/marker.ts
packages/g-canvas/tests/bugs/issue-367-spec.js

- Close #367.
| 🇺🇸 English | 🐞 Fix `marker` that path with relative command doesn't work. #367         |
| 🇨🇳 Chinese | 🐞 修复 `marker` 无法渲染 path 相对路径的问题。#367          |

fix(g-canvas): path with relative command should work for marker

---

packages/g-base/src/event/event-contoller.ts

- Ref: #370.
- 对于 `contextmenu` 引起的 `mousedown` 事件，没有必要设置 mousedownShape、mousedownPoint 等属性，仅做简单触发，因为这些属性会涉及到后续其他事件的模拟。
| 🇺🇸 English | 🐞 [g-base] Fix that incorrect handling for `mousedown` event resulted from `contextmenu` event. #370          |
| 🇨🇳 Chinese | 🐞 [g-base] 修复 `contextmenu` 引起的 `mousedown` 事件可能会引起其他事件的问题。#370          |

fix(g-base): should handle mousedown resulted from contextmenu event

---

packages/g-base/src/event/event-contoller.ts
packages/g-base/src/event/graph-event.ts
packages/g-base/src/types.ts
packages/g-base/tests/unit/event-spec.js
packages/g-canvas/tests/bugs/issue-drag-spec.js

* 处理拖拽到画布外面继续移动、松开鼠标
* 处理 mouseleave 未触发的特殊场景

feat(drag): drag out canvas

---

packages/g-base/src/event/event-contoller.ts
packages/g-base/tests/unit/event-spec.js

* 在空白处 drop
* 在画布继续拖拽、drop, dragenter, dragleave

feat(drag): drop on canvas

---

packages/g-base/src/abstract/canvas.ts
packages/g-base/src/event/event-contoller.ts
packages/g-base/tests/unit/canvas-spec.js
packages/g-base/tests/unit/event-spec.js

- Ref: #336.
- 设置鼠标样式时直接生效
- 支持 mousewheel 事件
| 🇺🇸 English | 🌟 [g-base] Support for `mousewheel` event. #383          |
| 🇨🇳 Chinese | 🌟 [g-base] 支持 `mousewheel` 事件。#383          |

feat(event): add mousewheel event

---

docs/api/general/element.en.md
docs/api/general/element.zh.md
packages/g-base/src/abstract/container.ts
packages/g-base/src/abstract/element.ts
packages/g-base/src/interfaces.ts
packages/g-canvas/tests/bugs/issue-384-spec.js

- Close #384.
| 🇺🇸 English | 🌟 [g-base] Add `setZIndex(zIndex)` method for Element. #384          |
| 🇨🇳 Chinese | 🌟 [g-base] Element 新增 `setZIndex(zIndex)` 成员方法。#384          |

feat(g-base): add setZIndex method for Element

---

packages/g-canvas/src/shape/marker.ts
packages/g-svg/src/shape/marker/index.ts

- Ref: #305
| 🇺🇸 English | 🐞 [g-canvas & g-svg] Fix Marker not compatible with radius attr.         |
| 🇨🇳 Chinese | 🐞 [g-canvas & g-svg] 修复 Marker 不兼容 `radius` 绘图属性的问题。          |

fix(g-canvas & g-svg): should be compatible with radius attr for Marker

---

packages/g-canvas/src/shape/marker.ts
packages/g-canvas/tests/bugs/issue-392-spec.js

- Close #392;
| 🇺🇸 English | 🐞 [g-canvas] Fix Marker not work when `r` attr is 0. #392.          |
| 🇨🇳 Chinese | 🐞 [g-canvas] 修复 Marker 在绘图属性 `r` 为 0 时无法正常渲染的问题。#392.          |

fix(g-canvas): should work when r attr is 0 for Marker

---

packages/g-base/src/abstract/element.ts
packages/g-base/tests/unit/element-spec.js
packages/g-canvas/tests/bugs/issue-218-spec.js
packages/g-svg/src/util/draw.ts
packages/g-svg/tests/bugs/issue-388-spec.js

- Ref: #388;
| 🇺🇸 English | 🐞 [g-svg] Fix clipShape `remove` not work. #388          |
| 🇨🇳 Chinese | 🐞 [g-svg] 修复 clipShape 的 `remove` 方法导致渲染不生效的问题。#388          |

fix(g-svg): remove for clipShape should work

---

packages/g-svg/src/group.ts
packages/g-svg/src/util/svg.ts
packages/g-svg/tests/bugs/issue-388-spec.js

- Ref: #388;
| 🇺🇸 English | 🐞 [g-svg] Fix matrix animation for group not work. #388          |
| 🇨🇳 Chinese | 🐞 [g-svg] 修复 group 的矩阵动画不生效的问题。#388          |

fix(g-svg): matrix animation for group should work

---

docs/api/general/container.en.md
docs/api/general/container.zh.md
packages/g-base/src/abstract/container.ts
packages/g-base/src/interfaces.ts
packages/g-base/tests/unit/group-spec.js

| 🇺🇸 English | 🌟 [g-base] Add `getChildByIndex`, `contain` and `removeChild` method for Container. #295         |
| 🇨🇳 Chinese | 🌟 [g-base] Container 上新增 `getChildByIndex`, `contain` 和 `removeChild` 成员方法。 #295          |

feat(g-base): add getChildByIndex, contain and removeChild method for Container

---

packages/g-base/src/abstract/container.ts
packages/g-base/src/abstract/group.ts
packages/g-canvas/tests/bugs/issue-402-spec.js

- Close #402.
| 🇺🇸 English | 🐞 Fix canvas matrix change not affect `totalMatrix` of its children. #402          |
| 🇨🇳 Chinese | 🐞 修复 canvas 的矩阵变化不会影响子元素 `totalMatrix` 的问题。#402          |

fix(g-base): canvas matrix change should affect totalMatrix of its children

---

packages/g-base/src/event/event-contoller.ts

fix(g-base): should use ev object from upstream instead of global event

---

packages/g-base/src/abstract/container.ts
packages/g-canvas/tests/bugs/issue-407-spec.js

- Close #407.
| 🇺🇸 English | 🐞 Fix bbox for container contain `Infinity` and `-Infinity`. #407          |
| 🇨🇳 Chinese | 🐞 修复 Container 的包围盒计算会出现 `Infinity` 和 `-Infinity` 值的问题。#407          |

fix(g-base): bbox for container should not contain Infinity and -Infinity

---

packages/g-base/src/abstract/container.ts
packages/g-canvas/tests/bugs/issue-407-spec.js

- Fix #408.
- 修复 PR #408 中没有考虑的情况: 并不是所有的子元素的 `visible` 都是 `false`；

fix(g-base): #408 PR

---

packages/g-base/package.json
packages/g-base/src/util/text.ts
packages/g-base/tests/unit/bbox-spec.js

* 修复文本计算包围盒过程中，是数字的时候调用 includes、split 方法出现的问题

fix(bbox): string functions error

---

packages/g-base/src/abstract/container.ts
packages/g-base/src/event/event-contoller.ts
packages/g-base/src/interfaces.ts
packages/g-svg/src/canvas.ts
packages/g-svg/tests/bugs/issue-428-spec.js
packages/g-svg/tests/util.ts

- Close #428;
| 🇺🇸 English | 🐞 [g-svg] Fix event not work when matrix is applied. #428         |
| 🇨🇳 Chinese | 🐞 [g-svg] 修复元素设置了矩阵后事件不生效的问题。#428          |

fix(g-svg): event should work when matrix is applied

---

packages/g-base/package.json
packages/g-base/src/abstract/shape.ts
packages/g-base/src/types.ts
packages/g-base/tests/unit/bbox-spec.js
packages/g-canvas/tests/bugs/issue-shadow-spec.js

* 计算 canvasBBox 时附加 shadow 的包围盒

feat(bbox): shadow refresh

---

packages/g-base/src/bbox/path.ts
packages/g-canvas/tests/bugs/issue-436-spec.js

fix(g-base): should consider precision of angle calculation for Path

---

packages/g-canvas/package.json
packages/g-mobile/package.json
packages/g-svg/package.json
packages/g-webgl/package.json

refactor: use unpkg other than browser field in package.json

---

packages/g-canvas/src/canvas.ts
packages/g-canvas/tests/unit/canvas-spec.js

feat(pixelratio): round pixelRatio

---

packages/g-svg/src/util/dom.ts
packages/g-svg/tests/bugs/issue-462-spec.js

- Close #462.
| 🇺🇸 English | 🐞 [g-svg] Fix `toFront()` method not work. #462         |
| 🇨🇳 Chinese | 🐞 [g-svg] 修复 `toFront()` 方法不生效的问题。#462           |

fix(g-svg): toFront() method should work

---

packages/g-canvas/src/canvas.ts
packages/g-canvas/src/util/draw.ts
packages/g-canvas/tests/unit/canvas-draw-spec.js
packages/g-canvas/tests/unit/util/draw-spec.js

做了两个优化：
1. bbox 存在 NaN 的情况通过 width 和 height 进行判定， 0 的情况也过滤掉，无效的图形不会影响其他图形
2. 自动增加自动裁剪功能，最终计算的包围盒同窗口的包围盒相交。其他一些异常情况后续慢慢修改

Refresh bbox

---

packages/g-base/src/abstract/base.ts
packages/g-base/src/abstract/canvas.ts
packages/g-base/src/abstract/element.ts
packages/g-base/src/abstract/group.ts
packages/g-base/src/bbox/util.ts
packages/g-base/src/event/event-contoller.ts

refactor: remove some unused code

---

packages/g-canvas/src/util/arrow.ts

refactor: export Math function

---

packages/g-math/src/line.ts

refactor: replace line box function with getBBoxByArray

---

packages/g-svg/src/canvas.ts
packages/g-svg/src/defs/arrow.ts
packages/g-svg/src/defs/clip.ts
packages/g-svg/src/defs/gradient.ts
packages/g-svg/src/defs/index.ts
packages/g-svg/src/defs/pattern.ts
packages/g-svg/src/defs/shadow.ts
packages/g-svg/src/group.ts
packages/g-svg/src/util/dom.ts

Refactor(g-svg): add createSVGElement function

---

packages/g-math/src/util.ts
packages/g-math/tests/unit/util-spec.js

feat: g-math add getBBoxRange

---

packages/g-base/src/abstract/base.ts
packages/g-base/src/abstract/container.ts
packages/g-base/src/abstract/element.ts
packages/g-base/src/interfaces.ts
packages/g-base/src/util/box.ts
packages/g-base/src/util/util.ts
packages/g-canvas/src/canvas.ts
packages/g-canvas/src/shape/base.ts
packages/g-canvas/src/util/hit.ts
packages/g-canvas/tests/unit/shape/image-spec.js
packages/g-canvas/tests/unit/util/hit-spec.js
packages/g-canvas/tests/unit/util/quick-hit-spec.js

feat(getshape): quick hit in canvas

---

packages/g-base/src/abstract/canvas.ts
packages/g-base/tests/unit/event-spec.js
packages/g-canvas/src/canvas.ts
packages/g-svg/src/canvas.ts

g-base 中定义了 Canvas 对外提供 clearEvents() 方法，g-svg 中进行了复写，但 g-canvas 中并未复写
| 🇨🇳 Chinese |     复写 g-canvas 中的 clearEvents() 方法      |

fix(g-canvas): Add override of clearEvents()

---

packages/g-base/package.json
packages/g-base/src/abstract/element.ts
packages/g-canvas/tests/bugs/issue-drag-spec.js

chore(deps): bump @antv/matrix-util from 2.0.4 to 3.0.2

---

docs/api/canvas.en.md
docs/api/canvas.zh.md
packages/g-base/package.json
packages/g-base/src/abstract/canvas.ts
packages/g-base/src/event/event-contoller.ts
packages/g-base/src/interfaces.ts
packages/g-canvas/tests/bugs/issue-489-spec.js

- Close #489.
| 🇺🇸 English | 🐞 [g-base] Fix event not work when CSS transform is applied. #489         |
| 🇨🇳 Chinese | 🐞 [g-base] 修复画布容器应用 CSS transform 时，事件不生效的问题。#489          |

fix(g-base): event should work when CSS transform is applied

---

package.json
src/canvas.js
src/core/mixin/event.js
test/bugs/issue-489-spec.js

- Close #489.
| 🇺🇸 English | 🐞Fix event not work when CSS transform is applied. #489         |
| 🇨🇳 Chinese | 🐞 修复画布容器应用 CSS transform 时，事件不生效的问题。#489          |

fix(event): event should work when CSS transform is applied

---

packages/g-base/src/abstract/canvas.ts

fix(g-base): event => ev

---

src/shapes/path.js
test/bugs/issue-540-spec.js

- Close #540.
| 🇺🇸 English | 🐞Fix console errorwhen for Path when path attr length is 1. #540          |
| 🇨🇳 Chinese | 🐞 修复 Path 的路径数量为 1 时控制台抛错的问题。#540          |

fix(path): should work for Path when path attr length is 1

---

packages/g-canvas/src/canvas.ts
packages/g-canvas/tests/unit/canvas-spec.js

Pixel ratio v0.4

---

packages/g-base/package.json
packages/g-base/src/abstract/element.ts
packages/g-canvas/package.json
packages/g-canvas/src/canvas.ts
packages/g-canvas/tests/unit/canvas-draw-spec.js
packages/g-svg/package.json

fix(refresh): text refresh error

---

packages/g-canvas/package.json
packages/g-canvas/src/util/draw.ts
packages/g-canvas/tests/bugs/issue-group-spec.js
packages/g-canvas/tests/unit/canvas-refresh-spec.js

fix(g-canvas): 修复多层图形嵌套的刷新问题

---

packages/g-base/package.json
packages/g-base/src/abstract/element.ts
packages/g-canvas/package.json
packages/g-canvas/src/util/path.ts
packages/g-math/package.json

chore(deps): bump @antv/matrix-util from ^2.0.4 to ^3.1.0-beta.1

---

packages/g-canvas/package.json
packages/g-canvas/src/shape/path.ts
packages/g-canvas/src/util/path.ts
packages/g-canvas/tests/bugs/issue-long-path-spec.js
packages/g-math/package.json
packages/g-math/src/bezier.ts
packages/g-math/src/cubic.ts

fix: mouse event on long cubic path problem.

fix: mouse event on long cubic path problem.

---

packages/g-canvas/src/shape/image.ts

canvas 中设置图片跨域的 image.crossOrigin = 'Anonymous'; 需要放到 image.src 前面，否则还是会出现跨域错误。

fix: image cros

---

packages/g-canvas/src/util/draw.ts

fix: clear group and addGroup out of view problem, closes: #638

---

packages/g-base/package.json
packages/g-canvas/package.json
packages/g-math/package.json
packages/g-mobile/package.json
packages/g-svg/package.json
packages/g-webgl/package.json

添加src文件夹到files用于sourceMap
https://github.com/antvis/G2/issues/3053

chore: add src to files for sourceMap

---

packages/g-canvas/src/shape/marker.ts
packages/g-canvas/src/util/draw.ts
packages/g-canvas/tests/bugs/issue-688-spec.js

fix(issue-688): 当 marker symbol 没有内置时，method 为空，导致 crash

---

packages/g-base/package.json
packages/g-base/src/abstract/element.ts
packages/g-base/src/index.ts
packages/g-base/tests/unit/animate-spec.js

fix: canvas animate returns problem

fix: canvas animate returns problem

---

packages/g-canvas/src/canvas.ts
packages/g-canvas/tests/bugs/issue-726-spec.js
packages/g-canvas/tests/unit/canvas-spec.js

https://github.com/antvis/g/issues/726
When in a spa application, it's normal to create canvas in a detail page.But when router change, we go to another detail page while creating a new canvas instance.If I create too many, in ios, it will report Total canvas memory use exceeds xxx MB and show me a pure white canvas back.
I find some way to solve this bug, like
- https://stackoverflow.com/questions/52532614/total-canvas-memory-use-exceeds-the-maximum-limit-safari-12
- https://github.com/openlayers/openlayers/issues/9291
And I find the same way to deal in F2 https://github.com/antvis/F2/commit/ea3f84f4bcddb4d296b4977504121dd0a7cbc838.
So I wish G can support this for a better performance in mobile app.
none
| …

feat(g-canvas): fix webkit ios canvas garbage collection bug

---

packages/g-canvas/src/shape/line.ts

| 🇨🇳 Chinese |      更改备注     |

docs: 更改备注

---

package.json

chore: upgrade lerna version

---

packages/g-base/package.json
packages/g-base/src/bbox/text.ts
packages/g-base/src/index.ts

fix: remove padding when calc bbox of Text

---

packages/g-canvas/src/shape/text.ts
packages/g-canvas/tests/unit/shape/text-spec.js

fix(text-shape): 修复文本 shape，绘制了 null

---

packages/g-mobile/src/events.ts

- [√ ] Bug fix
none
scale的计算放业务侧更合适一些，在当前层不存在树结构的话不清楚初始的缩放比例
| 🇺🇸 English |     fix: directly  pass the scale value when on pinch    |
| 🇨🇳 Chinese |    fix: 直接透传缩放时的scale       |
- [ √] Doc is updated/provided or not needed
- [ √] Demo is updated/provided or not needed
- [√] TypeScript definition is updated/provided or not needed
- [ √] Changelog is provided or not needed

fix: 直接透传scale

---

packages/g-base/package.json
packages/g-base/src/index.ts

0.5.9 版本号升级

---

packages/g-canvas/package.json
packages/g-canvas/src/index.ts

chore: 0.5.8

---

packages/g-canvas/package.json
packages/g-canvas/src/index.ts

chore: 0.5.9

---

packages/g-base/package.json

- Bug fix
@antv/util新增函数max/min 且被引用
- Doc is updated/provided or not needed
- Demo is updated/provided or not needed
- TypeScript definition is updated/provided or not needed
- Changelog is provided or not needed

fix: util dependence version

---

packages/g-canvas/package.json
packages/g-canvas/src/index.ts

chore: 0.5.10

---

packages/g-canvas/src/shape/text.ts
packages/g-canvas/tests/unit/shape/text-spec.js

fix: 修复text为 0 的时候，导致不渲染

---

.fatherrc.ts
packages/g-canvas/.fatherrc.ts
packages/g-components/.fatherrc.ts
packages/g-components/src/Arrow.ts
packages/g-ecs/.fatherrc.ts
packages/g-ecs/tsconfig.json
packages/g-math/.fatherrc.ts
packages/g-plugin-3d/.fatherrc.ts
packages/g-plugin-canvas-picker/.fatherrc.ts
packages/g-plugin-canvas-renderer/.fatherrc.ts
packages/g-plugin-css-select/.fatherrc.ts
packages/g-plugin-dom-interaction/.fatherrc.ts
packages/g-plugin-svg-picker/.fatherrc.ts
packages/g-plugin-svg-renderer/.fatherrc.ts
packages/g-plugin-webgl-renderer/.fatherrc.ts
packages/g-svg/.fatherrc.ts
packages/g-webgl/.fatherrc.ts
packages/g/.fatherrc.ts

chore: change build config

---

packages/g-canvas/src/Canvas2DContextService.ts

#776 
移除 `$canvas` 时检查父元素，如有则移除。

fix: check canvas' parent when destroying #776

---

packages/g-canvas/package.json
packages/g-canvas/src/index.ts

chore: g-canvas v0.5.11

---

package.json
packages/g-components/src/Arrow.ts
packages/g-ecs/src/Component.ts
packages/g/src/CustomElement.ts
packages/g/src/DisplayObject.ts
packages/g/src/DisplayObjectPool.ts
packages/g/src/FederatedEvent.ts
packages/g/src/FederatedMouseEvent.ts
packages/g/src/__tests__/custom-element.spec.ts
packages/g/src/components/SceneGraphNode.ts
packages/g/src/components/Sortable.ts
packages/g/src/global-module.ts
packages/g/src/services/aabb/CircleUpdater.ts
packages/g/src/services/aabb/EllipseUpdater.ts
packages/g/src/services/aabb/LineUpdater.ts
packages/g/src/services/aabb/PathUpdater.ts
packages/g/src/services/aabb/PolylineUpdater.ts
packages/g/src/services/aabb/RectUpdater.ts
packages/g/src/services/aabb/TextUpdater.ts
packages/g/src/services/aabb/index.ts
packages/g/src/services/text/index.ts
packages/g/src/shapes-export.ts
packages/g/src/shapes-type.ts
packages/g/src/systems/Timeline.ts
packages/g/src/types.ts
packages/g/src/utils/text.ts

feat: 自定义组件添加生命周期

---

packages/g-mobile/src/canvas.ts
packages/g-mobile/src/events.ts

- [ √] Bug fix
error when call destroy function
| 🇺🇸 English |   fix(g-mobile): fix errors when call destroy function        |
| 🇨🇳 Chinese |  fix(g-mobile):  修复canvas destroy 函数报错         |

fix(g-mobile): 修复destroy错误

---

packages/g/src/dom/Node.ts
packages/g/src/dom/index.ts

fix: 修改dom/index.ts引入eventTarget.ts大小写问题

---

packages/g-plugin-3d/src/model/Grid.ts
packages/g-plugin-canvas-renderer/src/CanvasRendererPlugin.ts
packages/g-plugin-webgl-renderer/src/drawcall/Fill.ts
packages/g-plugin-webgl-renderer/src/drawcall/InstancedLine.ts
packages/g-plugin-webgl-renderer/src/drawcall/Line.ts
packages/g-plugin-webgl-renderer/src/drawcall/Text.ts
packages/g-plugin-webgl-renderer/src/material/Material.ts
packages/g-plugin-webgl-renderer/src/material/ShaderMaterial.ts
packages/g-plugin-webgl-renderer/src/platform/webgl2/Device.ts
packages/g/src/camera/Camera.ts
packages/g/src/global-module.ts
packages/g/src/property-handlers/index.ts
packages/g/src/property-handlers/lineDash.ts
packages/g/src/utils/math.ts
packages/site/docs/api/basic/display-object.en.md
packages/site/docs/api/basic/display-object.zh.md
packages/site/examples/camera/demo/perspective.js
packages/site/examples/event/index.en.md
packages/site/examples/gpgpu/index.en.md
packages/site/examples/plugins/index.en.md
packages/site/examples/shape/demo/image.js
packages/site/examples/shape/demo/line.js
packages/site/examples/shape/demo/polygon.js
packages/site/examples/shape/demo/polyline.js
packages/site/examples/shape/demo/text.js

feat: line/polyline/path/polygon 支持虚线, 透视相机支持 zoom #820

---

packages/g-plugin-webgl-renderer/.fatherrc.ts
packages/g-plugin-webgl-renderer/package.json
packages/g-plugin-webgl-renderer/src/drawcall/symbol/GlyphAtlas.ts
packages/g-plugin-webgl-renderer/src/index.ts
packages/g-webgl/package.json
packages/site/package.json

fix: inline potpack #836

---

packages/g-canvas/package.json
packages/g-components/package.json
packages/g-math/package.json
packages/g-plugin-3d/package.json
packages/g-plugin-canvas-picker/package.json
packages/g-plugin-canvas-renderer/package.json
packages/g-plugin-control/package.json
packages/g-plugin-css-select/package.json
packages/g-plugin-dom-interaction/package.json
packages/g-plugin-gpgpu/package.json
packages/g-plugin-html-renderer/package.json
packages/g-plugin-svg-picker/package.json
packages/g-plugin-svg-renderer/package.json
packages/g-plugin-webgl-renderer/package.json
packages/g-svg/package.json
packages/g-webgl/package.json
packages/g-webgpu-compiler/package.json
packages/g/package.json
packages/g/src/Canvas.ts
packages/g/src/display-objects/DisplayObject.ts
packages/g/src/dom/Element.ts
packages/g/src/dom/Node.ts
packages/g/src/dom/__tests__/animation.keyframe-effect.spec.ts
packages/g/src/dom/__tests__/document.spec.ts
packages/g/src/dom/__tests__/element.spec.ts
packages/g/src/dom/interfaces.ts
packages/g/src/types.ts
packages/site/package.json

fix: types error in displayobject

---

.github/workflows/auto-inspection.yml

ci: init surge action

---

.github/workflows/auto-inspection.yml

chore: using yarn

---

packages/g-mobile/src/shape/image.ts

image shape 在配置fill属性时，会导致绘制上一次结束的绘制，出现绘制混乱
| 🇺🇸 English |     fix image shape fill error      |
| 🇨🇳 Chinese |    修复image shape绘制错误       |

fix: 修复图片fill问题

---

docs/index.md
docs/renderComponent.tsx
packages/react-g/src/canvas.tsx
packages/react-g/src/index.ts
packages/react-g/src/reconciler.ts
packages/site/docs/guide/advanced-topics/use-react-g.en.md
packages/site/docs/guide/advanced-topics/use-react-g.zh.md

- [*] New feature
- [*] Site / Document optimization

feat[react-g]: 添加render函数

---

packages/g-base/package.json
packages/g-base/src/bbox/path.ts
packages/g-base/tests/unit/bbox-spec.js
packages/g-mobile/package.json
packages/g-mobile/src/canvas.ts

| 🇺🇸 English |     miniProgram support changeSize      |
| 🇨🇳 Chinese |    小程序端支持changeSize     |

Fix change size

---

.github/workflows/auto-inspection.yml

fix: 调整 surge 构建命令

---

.github/workflows/release-notify.yml

chore: add dingtalk-release-notify

---

packages/g-mobile/src/index.ts

feat: add mobile interaction plugin to g-mobile

---

packages/g-components/src/Arrow.ts
packages/g/src/display-objects/DisplayObject.ts
packages/g/src/display-objects/Image.ts
packages/g/src/display-objects/Text.ts
packages/g/src/display-objects/__tests__/path.spec.ts
packages/g/src/property-handlers/lineDash.ts
packages/g/src/utils/interpolation.ts
packages/site/docs/api/basic/image.en.md
packages/site/docs/api/basic/image.zh.md
packages/site/docs/guide/advanced-topics/custom-element.en.md
packages/site/docs/guide/advanced-topics/custom-element.zh.md
packages/site/docs/guide/diving-deeper/box2d.en.md
packages/site/docs/guide/diving-deeper/box2d.zh.md
packages/site/docs/guide/diving-deeper/yoga.en.md
packages/site/docs/guide/diving-deeper/yoga.zh.md

feat: support  in Image #814

---

package.json
packages/g-mobile/__tests__/canvas.spec.ts
packages/g-mobile/__tests__/util.ts
packages/g-mobile/src/canvas-element.ts
packages/g-mobile/src/canvas.ts
packages/g-mobile/src/index.ts

feat: 添加 g mobile canvas

---

packages/g-base/README.md
packages/g-base/package.json
packages/g-base/src/animate/register.ts
packages/g-base/src/animate/timeline.ts
packages/g-base/src/index.ts
packages/g-base/tests/unit/animate-spec.js
packages/g-canvas/src/util/parse.ts
packages/g-math/README.md

feat: add easing register, enable custom easing

---

.github/workflows/release-notify.yml

chore: 修复钉钉推送 底部链接 点击不生效

---

packages/react-g/src/util/debug.ts

fix: disable debug

---

packages/g-mobile/__tests__/canvas.spec.ts
packages/g-mobile/src/Canvas2DContextService.ts
packages/g-mobile/src/canvas-element.ts
packages/g-mobile/src/canvas.ts
packages/g-mobile/src/dom.ts

feat: creat canvas 为标准canvs

---

packages/g-mobile/src/utils.ts

feat: fix bug

---

jest.config.js
packages/g-plugin-html-renderer/src/HTMLRenderingPlugin.ts
packages/g/src/display-objects/__tests__/html.spec.ts
packages/site/examples/perf/demo/circle-path.js

chore: use projects and cov #995

---

packages/g/src/Canvas.ts
packages/g/src/utils/dom.ts

feat: canvas 的 width/height 优先使用 style width/height

---

.github/workflows/release-notify.yml

chore: 给 dingtalk nofity 添加一个头图

---

packages/react-g/src/components/Arrow.tsx
packages/react-g/src/components/index.ts
packages/react-g/src/host-elements.ts

react-g中，箭头的实现因为涉及到切线计算，用户需要拿到displayObject的ref再手动实现，对于react-g来说最好不要暴露g的ref，且箭头是一个常见需求，所以预置为一个箭头react组件提供给用户使用。

feat: react-g add Arrow component

---

packages/site/gatsby-browser.js

chore: complete gatsby-browser config

---

packages/g-base/package.json
packages/g-canvas/package.json
packages/g-math/package.json
packages/g-mobile/package.json
packages/g-svg/package.json

- @antv/g-base@0.5.12
- @antv/g-canvas@0.5.13
- @antv/g-math@0.1.9
- @antv/g-mobile@0.0.5
- @antv/g-svg@0.5.7
升级 d3-interpolate 到 v3
https://github.com/antvis/G2/issues/4423

Upgrade d3-interpolate

---

__tests__/unit/g-geature/canvas.spec.ts
__tests__/unit/g-geature/util.ts
packages/g-gesture/src/gesture.ts

fix: event 引用会被修改 & fix 双指时其中一个手指start不触发的情况

---

packages/g-base/package.json
packages/g-base/src/animate/timeline.ts

fix: revert forked d3-interpolate & color

---

packages/g-lite/src/plugins/EventPlugin.ts

fix: touch native event

---

packages/g-lite/src/display-objects/DisplayObject.ts
packages/g-plugin-canvas-renderer/src/CanvasRendererPlugin.ts
packages/g-plugin-canvas-renderer/src/shapes/styles/Default.ts
packages/g-web-animations-api/src/dom/KeyframeEffect.ts
packages/g-web-animations-api/src/utils/interpolation.ts

fix: 兼容ios9

---

packages/g-lite/src/css/parser/dimension.ts

fix: width is NaN

---

__tests__/unit/css/parser/points.spec.ts
packages/g-lite/src/css/StyleValueRegistry.ts
packages/g-lite/src/css/parser/points.ts
packages/g-lite/src/css/properties/CSSPropertyPoints.ts
packages/g-web-animations-api/src/utils/interpolation.ts

feat: points support interpolation

---

packages/g-gesture/src/gesture.ts
packages/g-lite/src/plugins/EventPlugin.ts
packages/g-lite/src/services/EventService.ts

feat: 添加取消事件

---

packages/g-gesture/src/gesture.ts

fix: 手势事件修改成同步触发

---

__tests__/unit/display-objects/display-object.dataset.spec.ts
__tests__/unit/dom/animation.cancel.spec.ts
packages/g-lite/package.json
packages/g-lite/src/display-objects/DisplayObject.ts
packages/g-lite/src/global-runtime.ts
packages/g-lite/src/utils/tapable/AsyncParallelHook.ts
packages/g-mobile-webgl/package.json
packages/g-plugin-device-renderer/package.json
packages/g-plugin-device-renderer/src/index.ts
packages/g-plugin-device-renderer/src/meshes/SDF.ts
packages/g-plugin-device-renderer/src/renderer/Rect.ts
packages/g-plugin-device-renderer/src/renderer/index.ts
packages/g-plugin-device-renderer/src/shader/instanced-line.vert
packages/g-plugin-device-renderer/src/shader/sdf.frag
packages/g-webgl/package.json
packages/g-webgpu/package.json
packages/g/package.json
packages/react-g/package.json
site/examples/3d/3d-basic/demo/force-3d.js
site/examples/perf/basic/demo/meta.json
site/examples/perf/basic/demo/rects.js

fix: use instanced array rendering simple rect(sdf)

---

packages/g-lite/package.json
packages/g-mobile-webgl/package.json
packages/g-plugin-annotation/package.json
packages/g-plugin-annotation/src/SelectablePlugin.ts
packages/g-plugin-annotation/src/index.ts
packages/g-plugin-annotation/src/selectable/AbstractSelectable.ts
packages/g-plugin-annotation/src/selectable/SelectableCircle.ts
packages/g-plugin-annotation/src/selectable/SelectablePolygon.ts
packages/g-plugin-annotation/src/selectable/SelectablePolyline.ts
packages/g-plugin-annotation/src/selectable/SelectableRect.ts
packages/g-plugin-annotation/src/tokens.ts
packages/g-plugin-device-renderer/package.json
packages/g-webgl/package.json
packages/g-webgpu/package.json
packages/g/package.json
packages/react-g/package.json
site/examples/plugins/annotation/demo/annotation.js

#1339
目前支持对 Polygon 和 Polyline 进行顶点增删，使用方式如下。
首先开启该特性：
```js
const annotationPlugin = new AnnotationPlugin({
enableDeleteAnchorsWithShortcuts: true, // 支持通过删除锚点删除顶点
});
```
然后可以配置锚点选中状态下的样式：
```js
const annotationPlugin = new AnnotationPlugin({
enableDeleteAnchorsWithShortcuts: true,
selectableStyle: {
// 锚点选中时的样式
selectedAnchorSize: 10,
selectedAnchorFill: 'red',
selectedAnchorFillOpacity: 1,
selectedAnchorStroke: 'blue',
selectedAnchorStrokeWidth: 10,
selectedAnchorStrokeOpacity: 0.6,
},
});
```
交互表现如下：
* 点击选中锚点（可以多选）后，按下 DELETE / ESC / Escape 键就可以完成删除
* 点击已选中的锚点，可以取消选择
* 取消选中 UI，同时会取消选中当前全部已选中的锚点
通过拖拽 “半锚点”（两个锚点间增加一个） 新增顶点，可以配置 “半锚点” 的样式：
```js
const annotationPlugin = new AnnotationPlugin({
enableDisplayMidAnchors: true, // 开启 “半锚点”
selectableStyle: {
midAnchorSize: 10,
midAnchorFill: …
```

feat: support adding & deleting vertex with anchor #1339

---

packages/g-plugin-annotation/package.json
packages/g-plugin-annotation/src/SelectablePlugin.ts
packages/g-plugin-annotation/src/selectable/SelectableImage.ts
packages/g-plugin-annotation/src/selectable/index.ts

feat: add selectable UI for Image #1349

---

packages/g-plugin-annotation/package.json
packages/g-plugin-annotation/src/index.ts
site/examples/plugins/annotation/demo/meta.json
site/examples/plugins/annotation/demo/selectable-image.js

feat: add getSelectableUI to annotation plugin

---

packages/react-g/README.md

fix: typo README demo attribute spelling error

---

site/docs/api/renderer/webgpu.en.md
site/docs/api/renderer/webgpu.zh.md

| 🇺🇸 English | [Update webgpu.en.md](https://github.com/antvis/G/commit/73812654ea71318864b73c4c13845baee75611dc) |
| 🇨🇳 Chinese |  [Update webgpu.zh.md](https://github.com/antvis/G/commit/c5d16b05b34f74ae5ccd62ee0674ef5c0a07bf86)  |

docs: typo fix

---

packages/g-lite/src/services/TextService.ts
packages/g-plugin-device-renderer/src/utils/tiny-sdf.ts

Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently

perf: faster getImageData

---

packages/g/package.json

fix: set sideEffects of @antv/g to true

---

.github/workflows/auto-release.yml
.github/workflows/version.yml
package.json
packages/g/package.json

Use changesets instead of semantic-release

---

.changeset/modern-bugs-walk.md
.github/workflows/auto-release.yml
.github/workflows/version.yml
package.json
packages/g/package.json

Declare sideEffects field in @antv/g as `true`

---

.changeset/modern-bugs-walk.md
.github/workflows/auto-release.yml
.github/workflows/version.yml
package.json
packages/g/package.json

Modify commit message of changesets to make it passing through commitlint

---

.changeset/stupid-schools-bow.md
packages/g-lite/src/css/StyleValueRegistry.ts
packages/g-lite/src/css/parser/path.ts
packages/g-lite/src/css/properties/CSSPropertyPath.ts
packages/g-plugin-device-renderer/src/meshes/Line.ts

fix: avoid overriding defXY when parsing path

---

.changeset/pretty-geckos-march.md
packages/g-lite/src/plugins/EventPlugin.ts
packages/g-lite/src/services/EventService.ts
packages/g-plugin-device-renderer/src/PickingPlugin.ts
packages/g-plugin-device-renderer/src/platform/interfaces.ts
packages/g-plugin-webgl-device/src/platform/Readback.ts
packages/g-plugin-webgpu-device/src/platform/Readback.ts
pnpm-lock.yaml
site/package.json

考虑到 preventDefault 无法及时作用于异步事件处理器，暂时改回同步拾取方式。WebGL / WebGPU 方案待调研。

fix: use sync way when picking

---

.changeset/warm-snakes-pump.md
packages/g-lite/src/Canvas.ts
packages/g-lite/src/global-runtime.ts
packages/g-lite/src/services/OffscreenCanvasCreator.ts
packages/g-lite/src/services/TextService.ts
packages/g-lite/src/services/aabb/TextUpdater.ts
packages/g-plugin-canvas-picker/src/CanvasPickerPlugin.ts
packages/g-plugin-canvas-picker/src/Image.ts
packages/g-plugin-canvas-renderer/src/shapes/styles/Default.ts
packages/g-plugin-device-renderer/src/TexturePool.ts
packages/g-plugin-device-renderer/src/meshes/Instanced.ts
packages/g-plugin-device-renderer/src/meshes/InstancedPath.ts
packages/g-plugin-device-renderer/src/meshes/Line.ts
packages/g-plugin-device-renderer/src/platform/utils/hash.ts
packages/g-plugin-device-renderer/src/renderer/BatchManager.ts
packages/g-plugin-device-renderer/src/utils/tiny-sdf.ts
site/examples/perf/animation/demo/webgl-text.js
site/examples/shape/text/demo/meta.json
site/examples/shape/text/demo/text-single-canvas.js
site/examples/style/gradient/demo/gradient-path.js
site/examples/style/gradient/demo/meta.json
site/examples/style/gradient/demo/radial-gradient.js

fix: draw empty Path correctly with webgl #1417 #1408

---

.changeset/honest-falcons-chew.md
packages/g-lite/src/global-runtime.ts

Fix globalthis

---

packages/g-plugin-canvas-path-generator/src/paths/Ellipse.ts

fix: fix arc position error

---

.changeset/lazy-starfishes-beg.md
packages/g-plugin-device-renderer/src/renderer/BatchManager.ts

fix: update textBaseline correctly in webgl

---

packages/g-gesture/src/gesture.ts

fix: 手势事件因为冒泡而多次绑定

---

.changeset/kind-starfishes-learn.md
.changeset/thirty-wasps-train.md
packages/g-gesture/src/gesture.ts
packages/g-plugin-rough-svg-renderer/src/index.ts
packages/g-plugin-zdog-svg-renderer/src/index.ts

fix: pass global runtime in svg element lifecycle contribution

---

.changeset/new-peas-doubt.md
packages/g-lite/src/Canvas.ts
packages/g-lite/src/types.ts
packages/g-lite/src/utils/canvas.ts
packages/g-plugin-canvas-renderer/src/CanvasRendererPlugin.ts
packages/g-plugin-device-renderer/src/PickingPlugin.ts
site/examples/canvas/container/demo/meta.json
site/examples/canvas/container/demo/shared-container.js

G6 中一个 container 需要支持容纳多个画布，开启 `supportsMutipleCanvasesInOneContainer` 后即可：
```js
const canvas1 = new Canvas({
container: 'container',
width: 500,
height: 500,
renderer: canvasRenderer1,
supportsMutipleCanvasesInOneContainer: true,
});
const canvas2 = new Canvas({
container: 'container',
width: 500,
height: 500,
renderer: canvasRenderer2,
supportsMutipleCanvasesInOneContainer: true,
});
```
另外修复两个插件中存在的 OOM 问题。

fix: support multiple canvases in one container

---

.changeset/fast-suns-juggle.md
__tests__/unit/display-objects/html.spec.ts
packages/g-plugin-html-renderer/src/HTMLRenderingPlugin.ts

fix: should allow different HTMLs sharing the same Id #1475

---

packages/g-gesture/src/gesture.ts

fix: 回滚手势全局触发，会带来严重的性能问题

---

.changeset/selfish-avocados-listen.md
packages/g-plugin-gesture/src/util.ts

chore: trigger changeset

---

packages/g-plugin-gesture/src/GesturePlugin.ts

fix: move过程中元素移除，重新获取target

---

.changeset/flat-grapes-remain.md
packages/g-plugin-gesture/src/GesturePlugin.ts

fix: 去掉 move 过程中添加point

---

.changeset/light-wolves-speak.md
packages/g-plugin-device-renderer/src/drawcalls/Instanced.ts

Fix instance

---

.changeset/flat-months-end.md
packages/g-plugin-gesture/src/GesturePlugin.ts

Fix: 修复touchend事件不触发导致手势异常

---

.changeset/flat-months-end.md
packages/g-plugin-gesture/src/GesturePlugin.ts

fix: 修复touchend事件不触发导致手势事件异常

---

packages/react-g/src/reconciler.ts

feat: 取消react-g的log打印 #1521

---

.changeset/bright-dryers-chew.md
packages/g-plugin-device-renderer/src/drawcalls/InstancedPath.ts

fix: marker's parentNode should not be null

---

.changeset/odd-bugs-kiss.md
packages/g-mobile-svg/package.json
packages/g-mobile-svg/src/index.ts
packages/g-mobile-webgl/package.json
packages/g-mobile-webgl/src/index.ts
pnpm-lock.yaml

fix(gesture): svg & webgl 手势事件不生效

---

.changeset/odd-bugs-kiss.md
packages/g-mobile-svg/CHANGELOG.md
packages/g-mobile-svg/package.json
packages/g-mobile-svg/src/index.ts
packages/g-mobile-webgl/CHANGELOG.md
packages/g-mobile-webgl/package.json
packages/g-mobile-webgl/src/index.ts
pnpm-lock.yaml

* fix(gesture): svg & webgl 手势事件不生效
* chore: commit changeset
---------

fix(gesture): svg & webgl 手势事件不生效 (#1539)

---

.changeset/friendly-ligers-greet.md
.changeset/little-panthers-glow.md
packages/g-mobile-webgl/package.json
packages/g-plugin-3d/package.json
packages/g-plugin-canvas-renderer/src/CanvasRendererPlugin.ts
packages/g-plugin-device-renderer/package.json
packages/g-plugin-device-renderer/src/drawcalls/Instanced.ts
packages/g-plugin-device-renderer/src/materials/Material.ts
packages/g-webgl/package.json
packages/g-webgpu/package.json
pnpm-lock.yaml
site/docs/api/3d/material.en.md
site/docs/api/3d/material.zh.md
site/package.json

fix: use stencil front & back in latest device api

---

.changeset/ten-boxes-love.md
packages/g-lite/src/services/RenderingService.ts
site/examples/perf/webgl/demo/nodes.js

fix: skip triggering render hooks when camera changed only.

---

packages/g-plugin-canvas-renderer/src/CanvasRendererPlugin.ts
packages/g-plugin-canvaskit-renderer/src/CanvaskitRendererPlugin.ts

fix: 小程序不存在 Node 对象

---

site/docs/api/basic/text.en.md
site/docs/api/basic/text.zh.md

| 🇺🇸 English |  fix invalid example path         |
| 🇨🇳 Chinese |  修复 API 文档 "文本" 章节错误链接        |

docs(text): fix invalid example path

---

.changeset/gold-spoons-taste.md
packages/react-g/src/reconciler.ts
site/examples/ecosystem/declarative/demo/meta.json
site/examples/ecosystem/declarative/demo/react-g-render.js

fix: use ownerDocument when finding document in element

---

packages/g-plugin-svg-renderer/src/SVGRendererPlugin.ts

fix: avoid generating redundant dom structure for document element #1578

---

.changeset/smart-kings-boil.md
.github/workflows/deploy.yml
packages/g-lite/src/services/OffscreenCanvasCreator.ts
packages/g-plugin-device-renderer/src/drawcalls/InstancedFill.ts
packages/g-plugin-device-renderer/src/renderer/Path.ts
packages/g-plugin-device-renderer/src/shader/mesh.vert
site/examples/3d/3d-basic/demo/billboard.js

Pass `willReadFrequently: true` when creating offscreen canvas.

fix: use willReadFrequently when creating offscreen canvas

---

.changeset/loud-waves-reflect.md
__tests__/demos/2d/circles.ts
__tests__/demos/lottie/index.ts
__tests__/demos/lottie/spring.ts
__tests__/main.ts
packages/g-lite/src/css/CSSProperty.ts
packages/g-lite/src/css/StyleValueRegistry.ts
packages/g-lite/src/css/interfaces.ts
packages/g-lite/src/css/parser/dimension.ts
packages/g-lite/src/css/parser/numeric.ts
packages/g-lite/src/css/parser/transform-origin.ts
packages/g-lite/src/css/parser/transform.ts
packages/g-lite/src/css/properties/CSSPropertyAngle.ts
packages/g-lite/src/css/properties/CSSPropertyLengthOrPercentage.ts
packages/g-lite/src/css/properties/CSSPropertyNumber.ts
packages/g-lite/src/css/properties/CSSPropertyOffsetDistance.ts
packages/g-lite/src/css/properties/CSSPropertyOpacity.ts
packages/g-lite/src/css/properties/CSSPropertyTransform.ts
packages/g-lite/src/css/properties/CSSPropertyTransformOrigin.ts
packages/g-lite/src/css/properties/CSSPropertyZIndex.ts
packages/g-lite/src/display-objects/DisplayObject.ts
packages/g-web-animations-api/src/utils/interpolation.ts

fix: disable memoize during interpolation #1618

---

.changeset/pre.json

chore: commit changeset

---

.changeset/big-wasps-scream.md
.changeset/old-turtles-run.md
packages/g-plugin-a11y/src/TextExtractor.ts
packages/g-plugin-rough-canvas-renderer/src/util.ts
packages/g-plugin-rough-svg-renderer/src/util.ts

Fix rough plugin

---

.changeset/breezy-tables-build.md
packages/g-lite/src/services/EventService.ts

fix: make sure offset widht & height existed

---

.changeset/chatty-weeks-add.md
packages/g-lite/package.json
pnpm-lock.yaml

fix: update d3-color to solve vulnerable problem

---

__tests__/demos/plugin/yoga-text.ts
packages/g-plugin-matterjs/src/MatterJSPlugin.ts
site/package.json

chore: lock dumi version

---

__tests__/demos/plugin/yoga-text.ts
packages/g-plugin-matterjs/src/MatterJSPlugin.ts
site/package.json

chore: lock dumi version (#1707)

---

packages/g-camera-api/CHANGELOG.md
packages/g-camera-api/package.json
packages/g/CHANGELOG.md
packages/g/package.json
packages/react-g/CHANGELOG.md
packages/react-g/package.json

chore: update version

---

__tests__/demos/plugin/camera.ts
__tests__/demos/plugin/index.ts
packages/g-camera-api/src/AdvancedCamera.ts

* 修复 gotoLandmark 配置 `duration` 为 0 时不生效的问题
---
* Fixed an issue where gotoLandmark configuration `duration` would not take effect when set to 0

fix: fix gotoLandmark duration 0 not effect

---

packages/g-devtool/devtools/manifest.json
packages/g-devtool/devtools/script/panel.js
packages/g-devtool/package.json
packages/g-devtool/webpack.config.js

refactor: fix dev tools

---

.changeset/fair-avocados-jam.md

* chore: setup env of vite dev
* test: update dev demos
* chore: setup vite config
* chore: use different config in dev and ci env
* fix: vite development server webgl package exception
---------
Co-authored-by: wang1212 <mrwang1212@126.com>

fix dependency version information

---

.browserslistrc
.changeset/two-tips-guess.md

chore: revert build target

---

.changeset/friendly-stingrays-buy.md
packages/g-lite/src/utils/canvas.ts

fix: fix issue canvas cannot destroy

---

.changeset/eighty-waves-enjoy.md
.changeset/young-kids-pump.md
packages/g-plugin-canvas-renderer/src/CanvasRendererPlugin.ts
packages/g-plugin-canvas-renderer/src/shapes/styles/Default.ts
packages/g-plugin-canvas-renderer/src/shapes/styles/interfaces.ts
packages/g-plugin-image-loader/src/RefCountCache.ts

The rough canvas plugin reports an error when drawing.
This is because there is a bug in the code that was not fully tested during the refactoring process. Native canvas and rough canvas share the same code, which should not be decoupled from the core as the implementation of native canvas.
| 🇺🇸 English | fix: rough canvas rendering error |
| 🇨🇳 Chinese | fix: rough canvas 渲染异常 |

fix: rough canvas rendering error

---

.changeset/kind-ligers-melt.md
packages/g-plugin-3d/src/lights/DirectionalLight.ts

fix: fix dirctional light error

---

.changeset/small-ravens-rescue.md
__tests__/unit/abstract-renderer.spec.ts
packages/g-lite/src/display-objects/DisplayObject.ts

refactor: cloneNode copy complete config

---

.github/workflows/release.yml
.github/workflows/version.yml

chore: update workflows

---

.github/workflows/codeql.yml
.github/workflows/deploy.yml
.github/workflows/release.yml

| 🇺🇸 English | ci: update workflow config |
| 🇨🇳 Chinese | ci: 更新工作流配置 |

ci: update workflow config

---

.github/workflows/moderator.yml
.github/workflows/welcome-new-contributors.yml

- Add AI Moderator workflow for spam and AI content detection
- Add Welcome New Contributors workflow for first-time contributors

chore: add GitHub Actions workflows for community management

---

.github/workflows/discussion-automated.yml
.github/workflows/issue-automated.yml
.github/workflows/scripts/issue-automated.js

https://github.com/antvis/G/issues/1959#issuecomment-3290638836
https://github.com/antvis/G/issues/1712#issuecomment-3290652515
https://github.com/antvis/G/discussions/1967#discussioncomment-14400163
| 🇺🇸 English |    chore: auto AI reply        |
| 🇨🇳 Chinese |     chore: 对issue和Discussion开启AI自动回复       |

chore: auto AI reply 
