antvis/G

- src/util/dom.js
- test/unit/util/dom-spec.js
in React, container of a Chart is sometimes destroyed while Chart instance is still there.
antvis/g2#241
> fix(util): avoid crushing when calling DOMUtil methods with invalid DOMNode

- src/canvas/shape/image.js
对于导出的 canvas，若包含跨域图片，则会造成 canvas 污染；增加跨域支持后可以解决这个问题
#40
> feat($browser): 图片增加跨域支持

- src/core/group.js
We should check destroyed before actually run clear. Otherwise the `_cfg,children` will be `undefined` and 
cause `children.length` throw an error.
The PR is intent to fix a downstream [issue](https://github.com/antvis/g2/issues/1097).
> fix(group): check destroyed before clear

- src/shapes/marker.js
关联 issue https://github.com/antvis/g2/issues/1158
> fix(marker): compatible with scenes where symbol does not exist

- src/core/mixin/event.js
解决shape上的点击事件不一定被捕获的问题。
参考[G6 issues: 732](https://github.com/antvis/g6/issues/732)
> fix: g6 issue#732

- src/shapes/text.js
- test/bugs/text-height-update-spec.js
当文本从多行文本更新为单行文本是，文本的 bbox 高度计算不正确，根本原因是由于没有更新 lineCount属性，bug 重现代码如下：
```
const canvas = new G.Canvas({
containerId: 'canvas-dom',
width: 200,
height: 200,
pixelRatio: 2,
renderer: 'svg'
});
const lineWidth = 1;
const text = new G.Text({
attrs: {
x: 50,
y: 50,
text: '你好啊\n你好啊\n你好啊',
lineHeight: 14,
fontSize: 14,
lineWidth,
}
});
// console.log((text.getBBox().height - lineWidth)/3);
console.log(text.getBBox().height);
text.attr({text: '你好啊'});
console.log(text.getBBox().height);
// console.log(text.getBBox().height - lineWidth);
canvas.add(text);
canvas.draw();
```
> 当文本从多行更新为单行时，bbox 的高度计算不正确（没有更新属性lineCount）

- packages/g-canvas/__tests__/unit/shape/image-spec.js
- packages/g-svg/src/shape/base.ts
- Broken CI link: https://travis-ci.org/antvis/g/builds/578682304
> fix(ci): bbox should contains x and y attribute

- packages/g-svg/src/canvas.ts
- `g-svg` supports `event` implemented from `g-base`.
> feat(g-svg): event

- lerna.json
- 暂不发版的包 `@antv/g-mobile` 和 `@antv/g-webgl` 就算设为 `"private": true`，依然会打 `tag`，并出现在 `publish` 记录里。因此需要在 `lerna.json` 中手动指定 `packages` 字段。
> fix(lerna): not to publish and tag g-mobile and g-webgl for now

- packages/g-canvas/__tests__/bugs/issue-187-spec.js
- packages/g-canvas/__tests__/mocha.opts
- packages/g-canvas/src/canvas.ts
- Close #187 
- 修改 `canvas` 元素的宽、高属性，会使得 `context.scale()` 失效。因此根据 `pixelRatio` 去做缩放需要在渲染时进行，而不是画布初始化时去做。
| 🇺🇸 English | 🐞 修复 g-canvas 根据 `pixelRatio` 进行缩放操作不生效的问题。#187 |
| 🇨🇳 Chinese | 🐞 Fix that `context.scale()` is not effective according to `pixelRatio` for g-canvas. #187 |
> fix(g-canvas): context scale should be effective

- packages/g-canvas/__tests__/unit/canvas-spec.js
- packages/g-canvas/src/canvas.ts
- None.
- For `g-canvas`, `autoDraw` should be true by default.
| 🇺🇸 English | 🐞 修复 g-canvas 的自动绘制功能没有默认开启。           |
| 🇨🇳 Chinese |  🐞 Fix that `autoDraw` should be true by default for g-canvas.          |
> fix(g-canvas): autoDraw should be true by default

- packages/g-svg/__tests__/bugs/issue-191-spec.js
- packages/g-svg/src/canvas.ts
- Close #191.
- 执行和停止动画时，渲染更新是根据 `autoDraw` 来决定是否自动调用 `canvas.draw()`:
```js
// timeline.ts
const autoDraw = this.canvas.get('autoDraw');
// 非自动更新模式下，需要手动更新
if (!autoDraw) {
this.canvas.draw();
}
```
- `g-svg` 只支持自动渲染模式，但却没有设置 `autoDraw: true`，使得动画执行时会调用 `canavs.draw()`，导致生成多个 SVG 元素。因此需要设置 `autoDraw: true`，且外部不可修改，避免出现 #191 中的问题。
| 🇺🇸 English | 🐞 Fix redundant rendering for g-svg when animating. #191          |
| 🇨🇳 Chinese | 🐞 修复 g-svg 执行动画时同一元素重复渲染的问题。#191 |
> fix(g-svg): autoDraw should be true and immutable to avoid redundant rendering when animating

- packages/g-base/__tests__/unit/animate-spec.js
- packages/g-canvas/__tests__/bugs/issue-187-spec.js
- packages/g-canvas/src/canvas.ts
- packages/g-svg/__tests__/bugs/issue-191-spec.js
- Close #187.
- #188 这个 PR 虽然能使得 `context.scale()` 生效，但会影响动画:
- #187 中的本质问题是设置 canvas 元素的宽度和高度，会重置缩放，因此 `context.scale `需要在每次设置宽、高后调用:
```js
setDOMSize(width: number, height: number) {
super.setDOMSize(width, height);
const context = this.get('context');
const el = this.get('el');
const pixelRatio = this.getPixelRatio();
el.width = pixelRatio * width;
el.height = pixelRatio * height;
// 设置 canvas 元素的宽度和高度，会重置缩放，因此 context.scale 需要在每次设置宽、高后调用
if (pixelRatio > 1) {
context.scale(pixelRatio, pixelRatio);
}
}
```
| 🇺🇸 English | 🐞 Fix that `context.scale()` is not effective according to `pixelRatio` for g-canvas. #187          |
| 🇨🇳 Chinese | 🐞 修复 g-canvas 根据 `pixelRatio` 进行缩放操作不生效的问题。#187           |
> fix(g-canvas): pixelRatio should be effective

- packages/g-base/__tests__/unit/animate-spec.js
- packages/g-base/src/abstract/element.ts
- Close #199.
- 动画覆盖的逻辑应该为:
- 动画覆盖应该要考虑动画延迟(delay) 和开始时间(startTime)；
- 无动画延迟时，对于同一属性的相同动画，后一个动画应该覆盖前一个动画；
| 🇺🇸 English | 🐞 Fix the logic of animation cover. #199           |
| 🇨🇳 Chinese | 🐞 修复动画逻辑覆盖不正确的问题。#199          |
> fix(g-base): animation cover

- packages/g-canvas/__tests__/bugs/issue-206-spec.js
- packages/g-canvas/src/util/draw.ts
- Close #206.
- Non-array value is equivalent to empty array for `lineDash` attribute.
| 🇺🇸 English | 🐞 [g-canvas] Fix that non-array value is not compatible with lineDash. #206 |
| 🇨🇳 Chinese | 🐞 [g-canvas] 修复 `lineDash` 为非数组值时页面报错的问题。 #206 |
> fix(g-canvas): make non-array value compatible with lineDash

- packages/g-base/src/event/event-contoller.ts
- packages/g-svg/tests/bugs/issue-205-spec.js
- Close #205.
- Two of event types should be considered:
- From `canvas` to `shape`;
- From `shape` to `canvas`;
| 🇺🇸 English | 🐞 [g-svg] Fix that `mouseenter` and `mouseleave`  is not effective. #205 |
| 🇨🇳 Chinese | 🐞 [g-svg] 修复 `mouseenter` 和 `mouseleave`  事件监听不生效的问题。#205 |
> fix(g-svg): mouseenter and mouseleave should be effective

- packages/g-canvas/__tests__/bugs/issue-202-spec.js
- packages/g-canvas/tests/bugs/issue-222-spec.js
- packages/g-math/src/arc.ts
- packages/g-math/tests/unit/ellipse-arc-spec.js
- Close #222.
| 🇺🇸 English | 🐞 [g-canvas] Fix that bbox calculation is not correct for `path` with `arc`. #222 |
| 🇨🇳 Chinese | 🐞 [g-canvas] 修复带有圆弧 `path` 的包围盒计算不正确的问题。#222 |
> fix(g-canvas): bbox calculation should be correct for path with arc

- packages/g-base/README.md
- packages/g-base/package.json
- packages/g-base/src/abstract/base.ts
- packages/g-base/src/event/event-contoller.ts
- packages/g-base/src/interfaces.ts
- packages/g-base/tests/unit/base-spec.js
> 使用 @antv/event-emitter 替代内置的 ee

- packages/g-canvas/tests/bugs/issue-227-spec.js
- packages/g-svg/src/shape/marker/index.ts
- packages/g-svg/tests/bugs/issue-240-spec.js
- packages/g-svg/tests/unit/shape/marker-spec.js
- Close #240.
| 🇺🇸 English | 🐞 [g-svg] Fix incorrect path for `marker`. #240         |
| 🇨🇳 Chinese | 🐞 [g-svg] 修复 `marker` 的路径不正确的问题。#240          |
> fix(g-svg): should get correct path for marker

- packages/g-canvas/src/util/path.ts
- packages/g-canvas/tests/bugs/issue-254-spec.js
- Close #254.
| 🇺🇸 English | 🐞 [g-canvas] Fix that bbox calculation for path is incorrect when angle is 0 and π. #254.          |
| 🇨🇳 Chinese | 🐞 [g-canvas] 修复当 `path` 的夹角为 0 和 π 时，包围盒计算错误的问题。#254.          |
> fix(g-canvas): bbox calculation for path is incorrect when angle is 0 and π

- docs/api/canvas.en.md
- docs/api/canvas.zh.md
- docs/guide/getting-started.en.md
- docs/guide/getting-started.zh.md
- gatsby-config.js
- package.json
- https://github.com/antvis/g2plot/pull/174
- https://github.com/antvis/g/pull/251
重新定义了一下 gatsby-config.js 的配置，有一些不兼容。
> docs: Upgrade theme config

- packages/g-base/src/abstract/element.ts
- packages/g-base/src/animate/timeline.ts
- packages/g-base/src/util/color.ts
- packages/g-base/tests/unit/animate-spec.js
> fix: 渐变色无补间，直接赋值

- packages/g-canvas/src/util/path.ts
- packages/g-canvas/tests/bugs/issue-210-spec.js
- packages/g-canvas/tests/bugs/issue-232-spec.js
- packages/g-canvas/tests/bugs/issue-252-spec.js
- packages/g-canvas/tests/bugs/issue-254-spec.js
- Close #254.
| 🇺🇸 English | 🐞 [g-canvas] Fix that bbox calculation is not correct for `path` when angle is null, 0 and PI. #254  |
| 🇨🇳 Chinese | 🐞 [g-canvas] 修复 `path` 的夹角为空、0 和 PI 时，包围盒计算不正确的问题。#254          |
> fix(g-canvas): bbox calculation should be correct for path when angle is null, 0 and PI

- packages/g-canvas/src/shape/text.ts
- packages/g-canvas/tests/bugs/issue-266-spec.js
- packages/g-canvas/tests/get-color.ts
- Close #266.
| 🇺🇸 English | 🐞 [g-canvas] Fix that `stroke` attr is not working for Text. #266         |
| 🇨🇳 Chinese | 🐞 [g-canvas] 修复 Text 的 `stroke` 属性不生效的问题。#266          |
> fix(g-canvas): stroke attr should be working for Text

- packages/g-svg/src/canvas.ts
- packages/g-svg/src/group.ts
- packages/g-svg/src/shape/base.ts
- packages/g-svg/src/util/dom.ts
- packages/g-svg/src/util/draw.ts
- packages/g-svg/tests/bugs/issue-276-spec.js
- Close #276 
- Just create dom when `parentNode` is null.
| 🇺🇸 English | 🐞 [g-svg] Fix that group.addShape should work when group dom is not created. #276      |
| 🇨🇳 Chinese | 🐞 [g-svg] 修复当图形分组没有对应的 `el` 元素时，调用 addShape 方法导致死循环的问题。#276          |
> fix(g-svg): group.addShape should work when group dom is not created

- packages/g-base/src/animate/timeline.ts
- packages/g-canvas/tests/bugs/issue-273-spec.js
- Close #273.
- Use identity matrix for interpolate when matrix is null.
| 🇺🇸 English | 🐞 [g-base] Fix that animation does not work when interpolate for null matrix. #273      |
| 🇨🇳 Chinese | 🐞 [g-base] 修复当对值为空的矩阵进行插值时，动画不生效的问题。#273          |
> fix(g-base): animation should work when interpolate for null matrix

- __tests__/unit/canvas/shape/text-spec.js
- src/shapes/text.ts
通过外部设置 text shape的`maxWidth`属性，设置text绘制的max-width，从而允许绘制更多文字
效果如下：
设置maxWidth后，字体缩小
> feat: 通过属性配置Text shape绘制的max width

- packages/g-svg/src/shape/base.ts
- packages/g-svg/tests/bugs/issue-276-spec.js
| 🇺🇸 English | 🐞 [g-svg] Fix that el maybe undefined when calculate bbox for shape.           |
| 🇨🇳 Chinese | 🐞 [g-svg] 修复计算图形的包围盒时，`el` 为空导致页面报错的问题。          |
> fix(g-svg): el maybe undefined when calculate bbox

- packages/g-canvas/src/util/arc-params.ts
- packages/g-canvas/src/util/path.ts
- packages/g-canvas/src/util/util.ts
- packages/g-canvas/tests/bugs/issue-287-spec.js
- Close #287 and #292.
- The case of start point and end pointer should be considered.
| 🇺🇸 English | 🐞 [g-canvas] Fix incorrect rendering for arc when start point and end point are same. #287 #292         |
| 🇨🇳 Chinese | 🐞 [g-canvas] 修复起点和终点相同时，弧形绘制不正确的问题。#287 #292         |
> fix(g-canvas): should render correctly when start point and end point are same for arc

- docs/api/shape/api.en.md
- docs/api/shape/path.en.md
- docs/api/shape/path.zh.md
- packages/g-base/src/index.ts
- packages/g-base/src/util/path.ts
- packages/g-canvas/src/shape/path.ts
- packages/g-canvas/src/util/path.ts
- packages/g-canvas/tests/unit/shape/path-spec.js
- packages/g-svg/src/shape/path.ts
- packages/g-svg/tests/unit/shape/path-spec.js
- Ref #295.
| 🇺🇸 English | 🌟 [g-canvas & g-svg] Add `getTotalLength()` method for Path. #295          |
| 🇨🇳 Chinese | 🌟 [g-canvas & g-svg] Path 上新增 `getTotalLength()` 成员方法。#295          |
> feat(g-canvas & g-svg): add getTotalLength method for path

- docs/api/shape/line.en.md
- docs/api/shape/line.zh.md
- examples/animation/onFrame/demo/along-line.js
- examples/animation/onFrame/demo/meta.json
- packages/g-canvas/src/shape/line.ts
- packages/g-canvas/src/shape/path.ts
- packages/g-canvas/tests/unit/shape/line-spec.js
- packages/g-canvas/tests/unit/shape/path-spec.js
- packages/g-svg/package.json
- packages/g-svg/src/shape/line.ts
- packages/g-svg/src/shape/path.ts
- packages/g-svg/tests/unit/shape/line-spec.js
- packages/g-svg/tests/unit/shape/path-spec.js
- Ref #295.
| 🇺🇸 English | 🌟 [g-canvas & g-svg] Add `getTotalLength()` and `getPoint(ratio)` method for Line. #295          |
| 🇨🇳 Chinese | 🌟 [g-canvas & g-svg] Line 新增 `getTotalLength()` 和 `getPoint(ratio)` 成员方法。#295          |
> feat(g-canvas & g-svg): add getTotalLength and getPoint method for Line

- packages/g-base/src/event/graph-event.ts
- packages/g-base/tests/unit/event-spec.js
- packages/g-canvas/src/util/arc-params.ts
- packages/g-canvas/tests/bugs/issue-326-spec.js
- Close #326.
- 另外，还将事件对象上的 `domEvent` 重命名为 `originalEvent`，以兼容自定义事件。
| 🇺🇸 English | 🐞 [g-canvas] Fix incorrect `partial rendering` for `arc path` when `rx` or `ry` is 0. #323          |
| 🇨🇳 Chinese | 🐞 [g-canvas] 修复 `弧形 path` 在长轴和短轴长度为 0 时，局部渲染不正确的问题。#323         |
> fix(g-canvas): partial rendering for arc path should be correct when rx or ry is 0

- packages/g-base/package.json
- packages/g-math/package.json
> fix(module): add module entry to avoid jest sourcemap is empty

- docs/api/canvas.en.md
- docs/api/canvas.zh.md
- docs/api/group.en.md
- docs/api/group.zh.md
- docs/api/shape/polyline.en.md
- docs/api/shape/polyline.zh.md
- packages/g-canvas/src/shape/polyline.ts
- packages/g-canvas/tests/unit/shape/polyline-spec.js
- packages/g-svg/src/shape/polyline.ts
- packages/g-svg/tests/unit/shape/polyline-spec.js
- Ref: #295.
| 🇺🇸 English | 🌟 [g-canvas & g-svg] Add `getStartTangent()` and `getEndTangent()` method for Polyline. #295           |
| 🇨🇳 Chinese | 🌟 [g-canvas & g-svg] Polyline 新增 `getStartTangent()` and `getEndTangent()` 成员方法。#295          |
> feat(g-canvas & g-svg): add getStartTangent() and getEndTangent() method for Polyline

- packages/g-base/src/abstract/element.ts
- packages/g-canvas/tests/bugs/issue-339-spec.js
- Close #339.
| 🇺🇸 English | 🐞 [g-base] Fix that `sort()` method doesn't work when `zIndex` is changed. #339         |
| 🇨🇳 Chinese | 🐞 [g-base] 修复当子元素的 `zIndex` 改变时，容器的 `sort()` 方法不生效的问题。#339          |
> fix(g-base): sort method should work when zIndex is changed

- docs/api/shape/attrs.en.md
- docs/api/shape/attrs.zh.md
- packages/g-canvas/src/shape/base.ts
- packages/g-canvas/src/shape/image.ts
- packages/g-canvas/src/shape/text.ts
- packages/g-canvas/tests/bugs/issue-342-spec.js
- packages/g-svg/src/shape/base.ts
- packages/g-svg/src/shape/rect.ts
- packages/g-svg/tests/bugs/issue-342-spec.js
- Close #342.
| 🇺🇸 English | 🐞 [g-canvas & g-svg] Fix that `opacity` attr for shape is `undefined` by default. #342  |
| 🇨🇳 Chinese | 🐞 [g-canvas & g-svg] 修复图形的 `opacity` 属性默认为空的问题。#342          |
> fix(g-canvas & g-svg): opacity attr for shape should be 1 by default

- src/canvas.js
- src/util/index.js
- test/bugs/issue-333-spec.js
- Close #333.
- 在 3.x 只简单处理 `scale` transform 函数，处理其他 transform 函数的完整方案将在 4.x 中实现。
| 🇺🇸 English | 🐞 Fix that canvas.getPointByClient() calculates incorrectly when container has CSS transform. #333          |
| 🇨🇳 Chinese | 🐞 修复当画布容器设置了 CSS transform 样式时，`canvas.getPointByClient()` 函数计算不正确的问题。#333          |
> fix(canvas): canvas.getPointByClient() should calculate correctly when container has CSS transform

- packages/g-base/src/event/event-contoller.ts
- packages/g-canvas/tests/bugs/issue-321-spec.js
- packages/g-svg/tests/bugs/issue-205-spec.js
- Close #321.
- Close #337.
- 这个问题实际上是由于 #221 中的修改，导致从图形离开画布时，会依次触发图形的 `mouseenter -> mouseleave -> mouseenter` 事件，表现起来就好像 `mouseleave` 事件没有触发一样。因此，需要避免前后两次不必要的 `mouseenter` 事件。
- 这次的修复方案会回滚掉 #221 的变更，后续还需要寻找其他的方案来修复 #221 中的问题。
| 🇺🇸 English | 🐞 [g-base] Fix that `mouseleave` event is not emitted from shape to outside of canvas directly. #321 #337          |
| 🇨🇳 Chinese | 🐞 [g-base] 修复从图形直接移动到画布外时，图形的 `mouseleave` 事件没有触发的问题。#321 #337          |
> fix(g-base): mouseleave evene should be emitted from shape to outside of canvas directly

- packages/g-base/src/event/event-contoller.ts
- packages/g-canvas/tests/bugs/issue-370-spec.js
- Close #370.
| 🇺🇸 English | 🐞 [g-base] Fix that `mouseup` and `click` event is emitted when `contextmenu` emitted. #370       |
| 🇨🇳 Chinese | 🐞 [g-base] 修复 `contextmenu` 事件会触发 `mouseup` 和 `click` 事件的问题。#370          |
> fix(g-base): mouseup and click event should not be emitted when contextmenu emitted

- packages/g-base/src/abstract/element.ts
- packages/g-canvas/src/canvas.ts
- packages/g-canvas/src/shape/base.ts
- packages/g-canvas/src/util/draw.ts
- packages/g-canvas/tests/bugs/issue-358-spec.js
- packages/g-svg/src/shape/base.ts
- packages/g-svg/src/shape/rect.ts
- Close #358.
- `父元素`、`祖先元素`、`canvas` 的 opacity 属性都会与子元素的 opacity 进行叠加(相乘处理)。
- `Element` 的默认 opacity 均为 1，包括 Canvas、Group 和 Shape。
| 🇺🇸 English | 🐞 [g-canvas] Fix that `opacity` attr should be composite with parent. #358          |
| 🇨🇳 Chinese | 🐞[g-canvas] 修复父子元素的 `opacity` 绘图属性无法叠加的问题。#358          |
> fix(g-canvas): opacity attr should be composite with parent

- packages/g-base/src/event/event-contoller.ts
- packages/g-canvas/tests/bugs/issue-drag-spec.js
- packages/g-canvas/tests/bugs/issue-mouseleave-spec.js
* 通过加个临时变量，如果是离开画布的事件，不重新设置 currentShape，下次 进入画布时会重置 currentShape，实现不算优雅，但是能够解决问题。其他的解决方案有：
+ 仅实现 mouseout 或者 mouseleave，在这个事件中触发两个事件
+ getShape 不通过当前 x,y 来判定，而通过离开画布边缘的位置进行判定，这个方案存在潜在的问题
> fix(mouseleave): fixed bug of mouseleave

- packages/g-base/src/event/event-contoller.ts
- packages/g-base/tests/unit/event-spec.js
- packages/g-canvas/tests/bugs/issue-380-spec.js
- Close #380.
-  `draggable: false` 时，对画布进行拖拽操作，事件响应顺序为: `mousedown -> mousemove -> mouseup -> click`;
- `draggable: true` 时，对画布进行拖拽操作，事件响应顺序为: `mousedown -> mousemove(是否触发取决于拖拽的速度和距离) -> dragstart -> drag -> dragend`;
| 🇺🇸 English | 🐞 [g-base] Fix that canvas could emit drag event when `draggable` is false. #380        |
| 🇨🇳 Chinese | 🐞 [g-base] 修复当 `draggable` 为 `false` 时，canvas 能够触发 `drag` 事件的问题。#380          |
> fix(g-base): should emit drag event for canvas only when draggable is true

- packages/g-base/src/abstract/element.ts
- packages/g-base/src/animate/timeline.ts
- packages/g-base/tests/unit/animate-spec.js
- Ref: #332.
| 🇺🇸 English | 🐞 [g-base] Fix `animate` method of Element not compatible with `onFrame` usage in 3.0 + Fix the error when value of function type is interpolated. #332          |
| 🇨🇳 Chinese | 🐞 [g-base] 兼容 3.0 中 `onFrame` 的用法 + 修复函数类型的绘图属性值进行动画插值时页面报错的问题。#332   |
> fix(g-base): compatible with previous onFrame usage and function cannot be interpolated

- packages/g-svg/src/shape/circle.ts
- packages/g-svg/src/shape/rect.ts
- packages/g-svg/tests/bugs/issue-388-spec.js
- Ref: 388;
| 🇺🇸 English | 🐞 [g-svg] Fix `opacity` attr not work for Rect. #388           |
| 🇨🇳 Chinese | 🐞 [g-svg] 修复 Rect 的 `opacity` 绘图属性不生效的问题。#388          |
> fix(g-svg): opacity attr for Rect should work

- packages/g-svg/src/shape/base.ts
- packages/g-svg/tests/bugs/issue-388-spec.js
- Ref: #388;
| 🇺🇸 English | 🐞 [g-svg] Fix `null` for fill and stroke attr not work. #388         |
| 🇨🇳 Chinese | 🐞 [g-svg] 修复 fill 和 stroke 绘图属性的 `null` 值不生效的问题。#388          |
> fix(g-svg): null for fill and stroke attr should work

- packages/g-svg/src/shape/line.ts
- packages/g-svg/src/shape/path.ts
- packages/g-svg/tests/unit/defs/arrow-spec.js
- `startArrow` 和 `endArrow` 的值为空时，图形对应的 el 既不设置 `marker-start` 和 `marker-end` 属性，也不生成对应的 `marker defs` 元素。
> fix(g-svg): should not create marker defs dom when startArrow or endArrow is false

- packages/g-svg/src/canvas.ts
- packages/g-svg/src/defs/index.ts
- packages/g-svg/src/group.ts
- packages/g-svg/src/interfaces.ts
- packages/g-svg/src/shape/base.ts
- packages/g-svg/src/util/draw.ts
- packages/g-svg/tests/bugs/issue-191-spec.js
- packages/g-svg/tests/bugs/issue-388-spec.js
- Ref: #388.
- 修复当收到调用 canvas.draw() 方法时，SVG 元素重复生成的问题
- 修复 `autoDraw` 无法修改的问题。
| 🇺🇸 English | 🐞 [g-svg] Fix svg elements generated repeatedly when canvas.draw(). #388         |
| 🇨🇳 Chinese | 🐞 [g-svg] 修复当收到调用 canvas.draw() 方法时，SVG 元素重复生成的问题。#388          |
> fix(svg): should not generate svg elements repeatedly when canvas.draw()

- packages/g-svg/src/group.ts
- packages/g-svg/src/interfaces.ts
- packages/g-svg/src/shape/base.ts
- packages/g-svg/tests/bugs/issue-388-spec.js
- Ref: #388;
- Ref: https://riddle.alibaba-inc.com/riddles/95caf617
| 🇺🇸 English | 🐞 [g-svg] Fix not work when autoDraw is false. #388        |
| 🇨🇳 Chinese | 🐞 [g-svg] 修复自动渲染模式无法正常运行的问题。#388          |
> fix(g-svg): should work when autoDraw is false

- packages/g-svg/src/defs/arrow.ts
- packages/g-svg/tests/unit/defs/arrow-spec.js
- Ref: #388;
| 🇺🇸 English | 🐞 [g-svg] Fix default arrow rendering not same with Canvas version. #388          |
| 🇨🇳 Chinese | 🐞 [g-svg] 修复默认的箭头渲染样式与 Canvas 版本不一致的问题。#388          |
> fix(g-svg): default arrow rendering should be same with Canvas

- packages/g-canvas/src/group.ts
- packages/g-canvas/src/shape/base.ts
- packages/g-canvas/tests/bugs/issue-382-spec.js
- Close #382;
- 对于 `group -> shape -> clip` 的结构，原先只有 group 上的 matrix 才会影响 clip 的拾取，而 shape 上的 matrix 则不会影响。因此会出现 #382 中，如果元素同时设置了 matrix 和 clip，会出现拾取不正确的问题。
| 🇺🇸 English | 🐞 [g-canvas] Fix incorrect hit when element has `matrix` and `clip` both. #382         |
| 🇨🇳 Chinese | 🐞 [g-canvas] 修复元素同时设置了 `matrix` 和 `clip` 时拾取不正确的问题。#382          |
> fix(g-canvas): matrix of element should affect its clip

- packages/g-canvas/src/canvas.ts
- packages/g-canvas/src/util/draw.ts
- packages/g-canvas/tests/bugs/issue-422-spec.js
- Close #422;
- 问题原因: `localRefresh: false` 为全局渲染，不会记录要更新的元素队列 `refreshElements`。但如果将 `localRefresh` 同步修改为 `true` 时，实际采用的却是局部渲染的逻辑，但之前又没有记录 `refreshElements`，因此局部渲染的刷新区域为空，导致实际不会渲染。
- 解决方案: 全局渲染模式下也需要记录更新的元素队列 `refreshElements`，渲染完成后同样需要置空。
| 🇺🇸 English | 🐞 [g-canvas] Fix no rendering when localRefresh change from false to true. #422         |
| 🇨🇳 Chinese | 🐞 [g-canvas] 修复渲染模式从全局渲染切换到局部渲染时，渲染结果不生效的问题。#422          |
> fix(g-canvas): should render when localRefresh change from false to true

- packages/g-base/src/abstract/element.ts
- packages/g-base/tests/unit/animate-spec.js
| 🇺🇸 English | 🐞 [g-base] Fix animate method of Element not compatible with `delay` and `repeat` usage in 3.0         |
| 🇨🇳 Chinese | 🐞 [g-base] 兼容 3.0 中动画接口中 `delay` 和 `repeat` 配置的用法。           |
> fix(g-base): delay and repeat should work in toAttrs for animate method

- packages/g-base/src/abstract/element.ts
- packages/g-base/tests/unit/animate-spec.js
- Ref PR: #424;
-`toAttrs.delay` 不应该生效，原先 3.x 也不支持这种写法，因此 4.0 也不需要兼容。
> fix(g-base): delay should not work in toAttrs

- __tests__/unit/canvas/shape/text-spec.js
- src/shapes/text.ts
- Close #429.
- 在 IE 浏览器下，对于 Canvas 的 fillText 和 strokeText 接口，maxWidth 为空会影响渲染，因此需要加上判断。
| 🇺🇸 English | 🐞 Fix no rendering for text in IE when maxWidth is nil. #429         |
| 🇨🇳 Chinese | 🐞 修复 Text 的 `maxWidth` 绘图属性为空时，在 IE 浏览器下无法绘制的问题。#429          |
> fix(text): no rendering for text in IE when maxWidth is nil

- packages/g-base/src/abstract/shape.ts
- packages/g-base/src/bbox/index.ts
- packages/g-base/src/bbox/line.ts
- packages/g-base/src/bbox/path.ts
- packages/g-base/src/bbox/points.ts
- packages/g-base/src/bbox/polygon.ts
- packages/g-base/src/bbox/polyline.ts
- packages/g-base/src/bbox/util.ts
- packages/g-canvas/src/shape/line.ts
- packages/g-canvas/src/shape/path.ts
- packages/g-canvas/src/shape/polyline.ts
- packages/g-canvas/src/util/arrow.ts
- packages/g-canvas/tests/bugs/issue-432-spec.js
- packages/g-canvas/tests/bugs/issue-436-spec.js
- packages/g-canvas/tests/unit/shape/polyline-spec.js
- Ref: #432.
- 箭头的包围盒最后决定还是放 bbox 了，毕竟也是图形的一部分。
| 🇺🇸 English | 🌟 [g-canvas] Arrow support for bbox calculation and hit. #432          |
| 🇨🇳 Chinese | 🌟 [g-canvas] 箭头支持包围盒计算和拾取。#432           |
> feat(g-canvas): arrow support bbox calculation and hit

- packages/g-canvas/src/canvas.ts
- packages/g-canvas/tests/bugs/issue-444-spec.js
* 部分用户经常会缩放浏览器，导致 pixelRatio 不是整数，在 1-2 之间时，图形刷新时会有残影，原因在于浏览器无法绘制非整数像素，都会多扩展出像素，目前在最终的包围盒外侧，各增加 0.5 个像素，这时候再取整，就会将超出的部分涵盖进来。
> fix(refresh): fixed bug #444

- packages/g-canvas/src/util/arrow.ts
| 🇺🇸 English | 🐞 [g-canvas] Fix `fill` attr not work for custom arrow.  |
| 🇨🇳 Chinese | 🐞 [g-canvas] 修复自定义箭头的 `fill` 绘图属性不生效的问题。           |
> fix(g-canvas): fill attr should work for custom arrow

- packages/g-base/src/util/path.ts
| 🇺🇸 English | The left side of the equation is an object while the right side is a number, which means they will never be equal. It seems a `.min` is missed for the levenshtein distance          |
| 🇨🇳 Chinese | 此处判断等号左边是对象，右边是数字永远不相等，从上下文看含义是取莱文斯坦距离，应该是漏写了`.min`          |
> fix(g-base): fix an condition judgement type error in path util

- packages/g-base/src/abstract/element.ts
- packages/g-base/src/event/event-contoller.ts
- packages/g-base/src/util/util.ts
- packages/g-base/tests/unit/event-spec.js
* 事件委托中，如果 toShape 和 fromShape 一致，则不在触发 mouseenter，mouseleave 事件
> feat(delegation): delegation mouseenter, mouseleave

- packages/g-base/src/event/event-contoller.ts
- packages/g-canvas/tests/bugs/issue-456-spec.js
- Close #456.
- 根据 MDN 对 [dragenter](https://developer.mozilla.org/zh-CN/docs/Web/API/Document/dragenter_event) 和 [dragleave](https://developer.mozilla.org/zh-CN/docs/Web/API/Document/dragleave_event) 事件规范的描述和定义，这两个事件可以冒泡。
| 🇺🇸 English | 🐞 [g-base] Fix that `dragenter` and `dragleave` events are unable to bubble. #456         |
| 🇨🇳 Chinese | 🐞 [g-base] 修复 `dragenter` 和 `dragleave` 事件无法冒泡的问题。#456          |
> fix(g-base): dragenter & dragleave event should be able to bubble

- packages/g-svg/src/shape/text.ts
- packages/g-svg/tests/bugs/issue-465-spec.js
- Close #465.
- 原先的逻辑应该是为了处理浏览器对 12px 字体的最小限制而做的 scale 处理，但实际测试下来，小于 12px 的字体在浏览器中也能正常渲染。再加上由于现在默认是自动渲染机制，做 scale 处理之后会不断触发字体渲染，导致死循环。因此去掉这一逻辑。
| 🇺🇸 English | 🐞 [g-svg] Fix text not rendered when `fontSize` < 12. #465           |
| 🇨🇳 Chinese | 🐞 [g-svg] 修复字体小于 `12px` 的文本无法正常渲染的问题。#465          |
> fix(g-svg): should not handle fontSize < 12 for text

- packages/g-base/src/abstract/element.ts
https://github.com/antvis/g/issues/451
原先在 element.pauseAnimate()中，仅通过 this.set('_pause', ...) 将 cfg._pase.isPaused 设置为 true ，但并未将 animation._paused 设置为 true 。
animation._paused 是一个优化更新性能的判断标记，仅在以下一处使用： https://github.com/antvis/g/blob/0e1fcb57c85ca1e1bc4d516b12791f05364af71b/packages/g-base/src/animate/timeline.ts#L91 
因此就算从未被设置为 true 也不会影响逻辑和测试，但就起不到优化的作用。
| 🇺🇸 English | set animation._paused to true in element.pauseAnimate() |
> fix(g-base): set animation._paused to true in element.pauseAnimate()

- packages/g-base/src/abstract/element.ts
在处理 mouseenter/mouseleave 的时候会不稳定出现错误，实际上这里检查 isParent 就暗示需要当前 element 是 Group 或者 Canvas了：
> fix: prevent undefined error when check isParent

- packages/g-base/src/abstract/element.ts
在 G2，当传入空数据进行绘制图表后，鼠标在图表上移动会报错。
> fix: 添加空判断，防止报错

- packages/g-canvas/src/shape/text.ts
- packages/g-canvas/src/util/in-path/point-in-path.ts
- packages/g-canvas/src/util/util.ts
> refactor: import @antv/g-base getOffScreenContext

- packages/g-base/src/abstract/element.ts
- packages/g-base/tests/unit/event-spec.js
委托事件时的 name 支持字符串或者数组，可以支持多个 name 的场景
> feat(delegate): name support array

- packages/g-canvas/package.json
- packages/g-canvas/src/canvas.ts
* 之前考虑 CanvasBBox 要包括 clip 的范围，所以 canvas 的 getCanvasBBox 改造了，但是最后没有实施，导致这个地方的定义同一般的 group 不一致，上层 G2的一些单元测试挂了。
> fix(canvas): getCanvasBBox removed

- packages/g-base/package.json
- packages/g-canvas/package.json
- packages/g-canvas/src/util/path.ts
- packages/g-math/package.json
- packages/g-math/src/line.ts
ref https://github.com/antvis/util/pull/37 、 https://github.com/antvis/G2/issues/2317
> 另外，可以设置 [antvis/gl-matrix](https://github.com/antvis/gl-matrix) Archive 掉，不用在维护了。
> fix(gl-matrix): use gl-matrix instead of antv/gl-matrix

- packages/g-canvas/src/util/hit.ts
这个地方判定出问题了，导致 canvas.getCanvasBBox 在每次拾取的时候调用，性能极大降低。
> fix(hit): canvas is not a group

- packages/g-base/package.json
- packages/g-base/src/abstract/element.ts
- packages/g-canvas/tests/bugs/issue-drag-spec.js
Reverts antvis/g#508
- ref: https://github.com/toji/gl-matrix/issues/389
> fix(deps): Revert "chore(deps): bump @antv/matrix-util from 2.0.4 to 3.0.2"

- package.json
- packages/g-canvas/src/canvas.ts
- packages/g-canvas/src/group.ts
- packages/g-canvas/src/shape/base.ts
- packages/g-canvas/tests/bugs/issue-380-spec.js
- packages/g-canvas/tests/bugs/issue-456-spec.js
- packages/g-canvas/tests/bugs/issue-494-spec.js
- Close #494.
| 🇺🇸 English | 🐞 [g-canvas] Fix render work incorrectly when element is clipped by view. #494          |
| 🇨🇳 Chinese | 🐞 [g-canvas] 修复当图形被视窗裁剪掉时，渲染不正常的问题。#494          |
> fix(g-canvas): render should work correctly when element is clipped by view

- __tests__/bugs/issue-556-spec.js
- src/canvas.ts
- src/core/base.ts
- src/renderers/canvas/painter.ts
- src/shapes/util/is-point-in-path-by-ctx.ts
- Close #556.
- 支持传入 `context` 以代替 `containerId` 属性配置，因为非浏览器环境无法根据 `containerId` 获取对应的容器 DOM，包括 G 内部创建 Canvas 节点的逻辑；
- `context` 上会挂载 canvas 节点对象，因此 el 可以正常获取；
- 同时还需要传入 `offscreenCanvas` 属性，因为 G 部分的拾取逻辑依赖离屏 Canvas，非浏览器环境下 G 同样无法内部创建离屏 canvas，需要外部传入。
| 🇺🇸 English | 🌟 Canvas supports `context` and `offscreenCanvas` props for non-browser env. #556          |
| 🇨🇳 Chinese | 🌟 Canvas 新增 `context` 和 `offscreenCanvas` 属性，以支持非浏览器环境 (比如小程序和 Node 端) 的渲染。#556          |
> feat(canvas): Support context and offscreenCanvas props for non-browser env

- packages/g-svg/src/shape/dom.ts
- packages/g-svg/tests/unit/shape/dom-spec.js
https://github.com/antvis/G6/issues/1765
Now the `html` attribute of the `dom` shape must be plain text. If the dom contains a `canvas`, it will not render correctly.
This change allows it to be a function, and the function can return text or dom elements. We can call the canvas rendering method in this function to make the canvas display correctly. Therefore, we can now customize the node with canvas-based library, such as echarts, threejs.
It should be noted that once the `draw` method of `registerNode` is overwritten, it will be called frequently, so the implementation of this function should be optimized.
> feat: attribute 'html' of dom shape can be a function

- packages/g-base/package.json
- packages/g-base/src/abstract/container.ts
- packages/g-base/src/bbox/path.ts
- packages/g-base/src/index.ts
- packages/g-canvas/package.json
- packages/g-canvas/src/group.ts
- packages/g-canvas/src/index.ts
- packages/g-canvas/src/util/draw.ts
- packages/g-math/package.json
- packages/g-math/src/util.ts
修复极大数据量，求最大值、最小值出错
依赖 https://github.com/antvis/util/pull/58 提供 `max`, `min` 方法，再做 `maxBy`, `minBy` 替换
> fix: 修复极大数量求最大值、最小值出错

- packages/g-mobile/src/util/mini-canvas-proxy.ts
- [ √] Bug fix
none
background:  opacity property of shape  didn't make effect
bug & solution:  canvas component in ant mini program  has no globalAlpha property，need to  add  in proxy。
| 🇺🇸 English |     fix(g-mobile): get globalAlpha problem in mini program      |
| 🇨🇳 Chinese |   fix(g-mobile): 修复小程序globalAlpha问题          |
> fix(g-mobile): get globalAlpha problem in mini program

- packages/g-mobile/src/util/mini-canvas-proxy.ts
- [ √] Bug fix
none
bug:   使用g-mobile，支付宝小程序里渲染不出图
solution:  代理canvas函数时，绑定this，防止调用时this丢失
| 🇺🇸 English |      fix(g-mobile): fix canvas proxy lost this problem in mini-program    |
| 🇨🇳 Chinese |     fix(g-mobile): 修复支付宝小程序里canvas代理丢失this问题      |
- [√ ] Doc is updated/provided or not needed
- [ √] Demo is updated/provided or not needed
- [ √] TypeScript definition is updated/provided or not needed
- [ √] Changelog is provided or not needed
> fix: mini-program canvas proxy problem

- packages/g-plugin-webgl-renderer/src/passes/CopyPass.ts
- packages/g-plugin-webgl-renderer/src/passes/RenderPass.ts
- packages/g-plugin-webgl-renderer/src/services/renderer/index.ts
- packages/g-plugin-webgl-renderer/src/services/renderer/regl/ReglModel.ts
- packages/g-plugin-webgl-renderer/src/services/renderer/regl/index.ts
- packages/g-plugin-webgl-renderer/src/services/shader-module/index.ts
#787 
支持在 WebGL 环境下自动转译 GLSL 1.0 到 3.0
> fix: auto transpile GLSL1.0 to 3.0 in WebGL2 context #787

- packages/react-g/src/reconciler.ts
相关issue：https://github.com/facebook/react/issues/19582
在react-g的reconciler实现中，在prepareForCommit中返回了`{}`，造成了应用崩溃
prepareForCommit相关文档：https://github.com/facebook/react/tree/main/packages/react-reconciler#prepareforcommitcontainerinfo
> fix: prepareForCommit返回值

- packages/g-base/package.json
- packages/g-base/src/animate/timeline.ts
https://github.com/antvis/G/issues/1282
依赖 fork 的 `@antv/d3-interpolate` 和 `@antv/d3-color`，仅对 package.json 做修改：
* `main` 字段指向正确的 CJS 产物
* 去除 `type: 'module'`
发布：
```
+ @antv/g-base@0.5.13
```
> fix: use @antv/d3-interpolate instead of d3-interpolate

- __tests__/unit/canvas.use-native-click.spec.ts
- __tests__/unit/g-gesture/canvas.spec.ts
- jest.config.js
- packages/g-gesture/src/gesture.ts
- packages/g-lite/src/Canvas.ts
- packages/g-lite/src/plugins/EventPlugin.ts
- packages/g-lite/src/services/EventService.ts
- packages/g-lite/src/services/RenderingService.ts
- packages/g-lite/src/types.ts
- packages/g-plugin-device-renderer/src/PickingPlugin.ts
- packages/g-plugin-device-renderer/src/RenderGraphPlugin.ts
- packages/g-plugin-device-renderer/src/meshes/Instanced.ts
- packages/g-plugin-device-renderer/src/platform/interfaces.ts
- packages/g-plugin-dom-interaction/src/DOMInteractionPlugin.ts
- packages/g-plugin-mobile-interaction/src/MobileInteractionPlugin.ts
- packages/g-plugin-webgl-device/src/platform/Readback.ts
- packages/g-plugin-webgpu-device/src/platform/Readback.ts
- site/examples/event/event-others/demo/meta.json
- site/examples/event/event-others/demo/use-native-click.js
之前 `click` 事件是通过组合监听 Pointer / Mouse / TouchEvent 模拟触发的。但在移动端环境发现有触发不正常现象，因此想直接监听原生 `click` 事件，这样是最准确的。
创建画布时增加一个 `useNativeClickEvent` 选项。`g-plugin-dom-interaction` 根据该选项决定是否监听原生 `click` 事件。
```js
const canvas = new Canvas({
container: 'container',
width: 600,
height: 500,
renderer,
useNativeClickEvent: true, // 开启
});
```
另外之前拾取设计成通用异步方式，导致在移动端环境触发事件后，preventDefault 不同步，因此暂时改回同步方式。
> feat: add useNativeClickEvent option

- packages/g-base/src/abstract/container.ts
- packages/g-canvas/src/util/draw.ts
我们使用g6的dagre展示依赖关系，节点数量高达**1w+**，每个节点比较复杂，包含6+个图元，所以图元总数在**6 * 1w+**;
当6k+节点时，滚动时开始卡顿，发现```checkRefresh```等函数耗时较长：
1. ```checkRefresh```下的```setChildrenRefresh ```存在递归设置refresh = true，在分组及图元较多时耗时较久；
2. 继续调研代码发现，对于隐藏的element，```drawChildren ```函数是跳过渲染的，也不会再走```base.draw```重置refresh=null；
3. 所以感觉可简化下逻辑吧，对于隐藏节点没必要递归设置refresh，可节省```setChildrenRefresh ```耗时；
- 改造```setChildrenRefresh ``` 函数，跳过已隐藏的element；
- 配合改造逻辑，优化```@antv/g6```的```scroll-canvas```组件，在滚动时隐藏视口外的element；
6k节点下```checkRefresh```耗时
有个优化后的大致滚动效果[demo](https://codesandbox.io/p/github/k644606347/g6-dagre-scroll-perf/main?workspaceId=b587cdfa-f66c-4f11-8642-7939499d4f77&file=%2FREADME.md) [git](https://github.com/k644606347/g6-dagre-scroll-perf)，不过@antv/g还是旧代码，得去node_modules里的@antv/g改成新代码，如何发布改动还没搞定🧎；
| …
> perf: 滚动性能优化

- .gitignore
- __tests__/unit/dom/animation.cancel.spec.ts
- demo/oom-animation.html
- packages/g-web-animations-api/src/dom/Animation.ts
#1329 
按照 WebAnimations API 规范：https://w3c.github.io/csswg-drafts/web-animations-1/#canceling-an-animation-section
调用 `animation.cancel()` 时，需要 reject finished 这个 Promise，然后再调用 oncancel 回调。
> fix: oncancel should be triggered when calling cancel on animation #1329

- site/docs/guide/diving-deeper/scenegraph.zh.md
I noticed some tables in the docs showing the problem:
It comes from https://g.antv.antgroup.com/guide/diving-deeper/scenegraph
I fixed it, noticing that the `|` character for the intersection type would conflict with Markdown table dividers, I replaced it with a `/`.
> docs(scenegraph): fix table

- packages/g-lite/src/css/StyleValueRegistry.ts
`runtime` 应该使用运行时传入的变量，而非全局版本。
> fix: use pass-in runtime instead of global

- .changeset/five-fans-know.md
- .changeset/tasty-clouds-marry.md
- __tests__/unit/display-objects/html.spec.ts
- packages/g-lite/src/display-objects/HTML.ts
- packages/g-plugin-device-renderer/src/PickingPlugin.ts
- packages/g-plugin-device-renderer/src/meshes/Instanced.ts
- packages/g-plugin-device-renderer/src/meshes/InstancedPath.ts
- packages/g-plugin-device-renderer/src/meshes/Line.ts
- packages/g-plugin-device-renderer/src/renderer/Path.ts
- site/examples/perf/webgl/demo/arrow.js
- site/examples/perf/webgl/demo/meta.json
- site/examples/perf/webgl/demo/rounded-rects.js
- site/examples/shape/polyline/demo/polyline.js
#1359
顶点数目相同的 Path 可以合并成同一个 draw call
> fix: combine multiple paths into a single drawcall

- .changeset/short-plants-fry.md
- .github/workflows/test.yml
- __tests__/unit/display-objects/html.spec.ts
- packages/g-plugin-html-renderer/src/HTMLRenderingPlugin.ts
> fix: remove redundant data-id on HTML

- .changeset/shaggy-knives-jam.md
- demo/perf-nodes-edges.html
- packages/g-camera-api/src/AdvancedCamera.ts
- packages/g-plugin-device-renderer/src/drawcalls/Instanced.ts
- packages/g-plugin-device-renderer/src/renderer/Batch.ts
> feat: add onframe param on camera animation

- .changeset/flat-apricots-remain.md
- __tests__/demos/plugin/annotation.ts
- __tests__/index.html
- __tests__/main.ts
- packages/g-lite/src/AbstractRenderer.ts
- packages/g-lite/src/Canvas.ts
- packages/g-lite/src/css/StyleValueRegistry.ts
- packages/g-lite/src/css/interfaces.ts
- packages/g-lite/src/display-objects/Ellipse.ts
- packages/g-lite/src/display-objects/Polygon.ts
- packages/g-lite/src/display-objects/Rect.ts
- packages/g-lite/src/global-runtime.ts
- packages/g-lite/src/plugins/PrepareRendererPlugin.ts
- packages/g-lite/src/types.ts
- packages/g-plugin-annotation/src/SelectablePlugin.ts
- packages/g-plugin-annotation/src/rendering/circle-render.ts
- packages/g-plugin-annotation/src/rendering/drawPoint-render.ts
- packages/g-plugin-annotation/src/rendering/drawline-render.ts
- packages/g-plugin-annotation/src/rendering/polygon-render.ts
- packages/g-plugin-annotation/src/rendering/polyline-render.ts
- packages/g-plugin-annotation/src/rendering/rect-render.ts
- packages/g-plugin-annotation/src/selectable/SelectableCircle.ts
- packages/g-plugin-annotation/src/selectable/SelectableImage.ts
- packages/g-plugin-annotation/src/selectable/SelectablePolygon.ts
- packages/g-plugin-annotation/src/selectable/SelectablePolyline.ts
- packages/g-plugin-annotation/src/selectable/SelectableRect.ts
- packages/g-plugin-annotation/src/selectable/SelectableRectPolygon.ts
- packages/g-webgl/src/index.ts
- packages/g-webgpu/src/index.ts
When using `@antv/g-plugin-annotation`, we want the anchors & lineWidth of selectable UI to keep the fixed size, which means camera's zooming won't affect them.
It's quite similar to [sizeAttenuation](https://threejs.org/docs/#api/en/materials/SpriteMaterial.sizeAttenuation) in Three.js.
Enabling `enableSizeAttenuation` will affect the selectable UI during initialization. When using drawer
```ts
import { runtime } from '@antv/g';
// Now canvas will listen to camera's changed event and modify each shape's `lineWidth` or `size` with `isSizeAttenuation` enabled.
runtime.enableSizeAttenuation = true;
const circle = new Circle({
style: {
r: 10,
isSizeAttenuation: true, // Enable this option when created.
}
});
``` …
> feat: support size attenuation in annotation plugin

- packages/g-base/src/abstract/container.ts
PR includes
ant-charts 双轴图 在 geometryOptions ==>> label ==>>  layout配置中启用 limit-in-plot报错
> fix(g-base): container类卸载后再去调用getChildren报错

- .changeset/lazy-mayflies-sleep.md
- .github/workflows/test.yml
- __tests__/demos/bugfix/1636.ts
- __tests__/demos/bugfix/index.ts
- __tests__/main.ts
- __tests__/unit/abstract-renderer.spec.ts
- jest.config.js
- packages/g-lite/src/services/SceneGraphService.ts
- packages/g-lite/src/services/aabb/RectUpdater.ts
#1636 
The bound of `clipPath` should be copied before doing calculation intersection.
> fix: clippath's bounds should be copied before intersection #1636

- __tests__/unit/display-objects/text.spec.ts
- __tests__/unit/offscreenCanvasContext.ts
- packages/g-lite/src/display-objects/Text.ts
> fix: update geometry before getting computed length #1651

- .changeset/witty-turtles-design.md
- __tests__/demos/3d/index.ts
- __tests__/demos/3d/webar.ts
- __tests__/main.ts
- packages/g-lite/package.json
- packages/g-lite/src/Canvas.ts
- packages/g-lite/src/camera/Camera.ts
- packages/g-lite/src/services/RenderingService.ts
- packages/g-plugin-device-renderer/package.json
- packages/g-plugin-device-renderer/src/RenderGraphPlugin.ts
- packages/g-plugin-device-renderer/src/drawcalls/Mesh.ts
- packages/g-plugin-device-renderer/src/index.ts
- packages/g-webgl/package.json
- packages/g-webgl/src/ARButton.ts
- packages/g-webgl/src/WebXRManager.ts
- packages/g-webgl/src/index.ts
- pnpm-lock.yaml
#1664 
参考 Three.js 的用法。提供默认的 ARButton：
```ts
import { ARButton } from '@antv/g-webgl';
const $button = ARButton.createButton(canvas, renderer, {});
container.appendChild($button);
```
点击后进入 AR 模式。
> feat: support ar in webxr

- .changeset/stale-eyes-provide.md
- __tests__/demos/3d/force.ts
- __tests__/demos/3d/webar.ts
- packages/g-plugin-device-renderer/src/RenderGraphPlugin.ts
> fix: sync proj & view matrix from webxr session

- .changeset/empty-buckets-decide.md
- __tests__/demos/bugfix/1677.ts
- __tests__/demos/bugfix/index.ts
- packages/g-lite/src/plugins/EventPlugin.ts
- packages/g-lite/src/services/EventService.ts
- packages/g-lite/src/types.ts
#1677 
`offsetX/Y` is unavailable in TouchEvent and shadow DOM.
`supportsCSSTransform` is enabled by default, so you don't need to set it manually.
> Correct mouse position even when scaling the container using CSS

- .changeset/blue-ants-decide.md
- __tests__/demos/3d/force.ts
- __tests__/demos/3d/webar.ts
- __tests__/main.ts
- packages/g-mobile-webgl/package.json
- packages/g-plugin-3d/package.json
- packages/g-plugin-device-renderer/package.json
- packages/g-plugin-device-renderer/src/RenderGraphPlugin.ts
- packages/g-webgl/package.json
- packages/g-webgpu/package.json
- pnpm-lock.yaml
In WebXR there're multiple XRViews e.g. left and right eyes. So we need to support rendering to cameras instead of a single camera.
https://threejs.org/docs/#api/en/cameras/ArrayCamera
Since we use RenderGraph now, each camera should have its own render pass.
```ts
this.cameras.forEach(({ viewport }) => {
// main render pass
this.builder.pushPass((pass) => {});
});
```
> fix: support cameras array

- .changeset/lazy-berries-pretend.md
- .changeset/real-coats-run.md
- __tests__/demos/bugfix/1572.ts
- __tests__/demos/bugfix/index.ts
- packages/g-plugin-canvas-renderer/src/index.ts
- packages/g-plugin-canvas-renderer/src/shapes/styles/Default.ts
- packages/g-plugin-canvas-renderer/src/shapes/styles/Text.ts
- packages/g-plugin-canvaskit-renderer/src/CanvaskitRendererPlugin.ts
- packages/g-plugin-svg-renderer/src/shapes/defs/Pattern.ts
> fix: support gradient text

- .changeset/blue-knives-breathe.md
- .changeset/sweet-apples-tease.md
- __tests__/demos/3d/cylinder.ts
- __tests__/demos/3d/force.ts
- __tests__/demos/3d/hit-test.ts
- __tests__/demos/3d/index.ts
- __tests__/demos/3d/sphere.ts
- __tests__/demos/3d/torus.ts
- __tests__/demos/bugfix/1636.ts
- __tests__/demos/bugfix/1667.ts
- __tests__/demos/bugfix/index.ts
- packages/g-lite/src/Canvas.ts
- packages/g-lite/src/camera/Camera.ts
- packages/g-plugin-device-renderer/src/RenderGraphPlugin.ts
- packages/g-webgl/src/WebXRController.ts
- packages/g-webgl/src/WebXRManager.ts
Use 2 render list for both left & right eyes.
Since we can't modify `projectionMatrix` according to Spec, we have to flipY with `viewMatrix`.
> It is strongly recommended that applications use this matrix without modification or decomposition.
https://immersive-web.github.io/webxr/#dom-xrview-projectionmatrix
https://github.com/mrdoob/three.js/blob/master/src/renderers/webxr/WebXRManager.js#L610
> Support left & right eyes

- packages/g-camera-api/src/AdvancedCamera.ts
`camera.gotoLandmark` 有一定概率不会执行 `onfinish`  回调函数
问题原因： `requestAnimationFrame` 计时误差导致小概率情况下 `elapsed === duration` 从而不会执行下一帧而无法执行 `endAnimation` 方法
---
`camera.gotoLandmark` will not execute the `onfinish` callback with some probability
Cause: a timing error in 'requestAnimationFrame' causes a small probability of 'elapsed === duration' which prevents' endAnimation 'from executing the next frame
> fix: fix sometime onfinish not invoke

- __tests__/demos/camera/index.ts
- __tests__/demos/camera/set-zoom-by-viewport-point.ts
- __tests__/main.ts
- packages/g-lite/src/camera/Camera.ts
setZoomByViewportPoint 在完成缩放后调整相机时，使用了 `pan` 操作来调整，导致相机视点位置没有同步更新
修正后：
缩放前后都通过 setPosition 和 setFocalPoint 来调整相机和视点位置
> fix: fix setZoomByViewportPoint

- .changeset/friendly-avocados-drum.md
- demo/camera+html.html
- packages/g-lite/src/display-objects/HTML.ts
- packages/g-lite/src/shapes/Rectangle.ts
Subtract the camera's transformation from the bounding box calculation logic of the `HTML` element to keep the result consistent with the native canvas element
- fixed #1743
Detailed questions can be found #1743 .
The root cause is that the camera transformation and element transformation of G are independent, which means that if only the camera is adjusted, the transformation of the canvas element will not change.
However, the implementation of `getBoundingClientRect()` of `HTML` type elements simply calls the DOM API, because the transformation of the camera `div` element as the parent element is also included, which is inconsistent with the calculation logic of the canvas element.
Therefore, the camera transformation needs to be eliminated in the implementation of …
> fix: `HTML` element bounding box calculation logic #1743

- .changeset/funny-tigers-leave.md
- packages/g-plugin-html-renderer/src/HTMLRenderingPlugin.ts
fixed #1702 
When the html canvas uses a div element as a container, the camera's transformation will be applied to the div element, so that after the user pans or zooms, the div cannot maintain the same width and height as the canvas element. As a container for rendering html elements, this will cause some problems, such as #1702 .
The solution is to add an additional div element as the html canvas container, whose direct child element is the camera's div element. In this hierarchical structure, the camera's transformation and rendering container are independent and do not affect each other. The html container div will always remain consistent with the canvas element.
| 🇺🇸 English | fix: HTML canvas does not match the canvas range …
> fix: HTML canvas does not match the canvas range after the camera is applied (#1702)

- packages/react-g/src/canvas.tsx
- packages/react-g/src/reconciler.ts
- site/docs/guide/advanced-topics/use-react-g.zh.md
When render component more than one times, it should reuse previous container.
> fix: fix g-react re-render

- .changeset/hungry-camels-remember.md
- packages/g-plugin-device-renderer/src/drawcalls/Text.ts
fixed #1755 
see #1755 
The solution is to add boundary condition judgment logic. When the number of objects to be updated is 0, the program will jump out directly.
| 🇺🇸 English |  fix: the logic boundary condition judgment of text element attribute update is missing (#1755)  |
| 🇨🇳 Chinese |  fix: text 元素的属性更新逻辑中缺少边界条件判断 (#1755) |
> fix: the logic boundary condition judgment of text element attribute update is missing (#1755)

- tsconfig.base.json
As shown in the figure, the `sources` file path in the generated map file is wrong.
This doesn't mean it won't work, it just reduces the debugging experience for developers.
According to the official TypeScript documentation, configuring [`sourceRoot`](https://www.typescriptlang.org/tsconfig/#sourceRoot) can solve this problem.
| 🇺🇸 English |  fix: `sourcemap.sources` path wrong         |
| 🇨🇳 Chinese |  fix: `sourcemap.sources` 路径错误        |
> fix: `sourcemap.sources` path wrong

- .changeset/healthy-boxes-train.md
- packages/g-plugin-device-renderer/src/drawcalls/Image.ts
- packages/g-plugin-device-renderer/src/drawcalls/Instanced.ts
- packages/g-plugin-device-renderer/src/drawcalls/InstancedFill.ts
- packages/g-plugin-device-renderer/src/drawcalls/InstancedLine.ts
- packages/g-plugin-device-renderer/src/drawcalls/InstancedPath.ts
- packages/g-plugin-device-renderer/src/drawcalls/Mesh.ts
- packages/g-plugin-device-renderer/src/drawcalls/SDF.ts
- packages/g-plugin-device-renderer/src/drawcalls/Text.ts
- tsconfig.base.json
…1768)
fixed #1768 
see #1768 
Reinitializing the geometry instance associated with the draw call instance with the latest element instance list before updating the attributes ensures correct rendering logic. And add boundary condition judgment.
| 🇺🇸 English | fix: webgl renderer has logical exception when updating attributes (#1768) |
| 🇨🇳 Chinese | fix: webgl 渲染器在更新属性时发生异常 (#1768)  |
> fix: webgl renderer has logical exception when updating attributes (#1768)

- .changeset/cool-crews-sneeze.md
- .prettierrc
- __tests__/demos/bugfix/1747.ts
- __tests__/demos/bugfix/index.ts
- packages/g-plugin-device-renderer/src/PickingPlugin.ts
- vite.config.mjs
---------
fixed #1747 
see #1747 
Because the y axis of the drawing coordinate system is downward, and the camera coordinate system is a right-handed coordinate system with its y axis pointing upward. Therefore, we only need to flip the y axis of the drawing coordinate system and pass it to the camera coordinate system.
| 🇺🇸 English | fix: wrong y coordinate when picking with webgl (#1747) |
| 🇨🇳 Chinese | fix: webgl 拾取时 y 坐标错误 (#1747) |
> fix: wrong y coordinate when picking with webgl (#1747)

- package.json
- prerelease 会导致发布过程进入 pre mode，原因不明
> chore: remove prerelease script

- .changeset/three-fishes-grow.md
- __tests__/demos/perf/canvas-api.ts
- __tests__/demos/perf/image.ts
- __tests__/demos/perf/javascript.ts
- package.json
- packages/g-lite/src/display-objects/DisplayObject.ts
- packages/g-lite/src/dom/Element.ts
- packages/g-lite/src/services/EventService.ts
- pnpm-lock.yaml
fixed #1813 
The current implementation of `Element.destroy()` only removes the element from the scene graph without destroying its child elements, which results in some cached resources not being released successfully, causing memory leaks.
When an element is destroyed, recursively destroying its child elements is the expected behavior.
| 🇺🇸 English | fix: when an element is destroyed, its child elements are not destroyed |
| 🇨🇳 Chinese | fix: 元素销毁时未销毁子元素 |
> fix: when an element is destroyed, its child elements are not destroyed

- .changeset/purple-suns-retire.md
- packages/g-plugin-image-loader/src/LoadImagePlugin.ts
When image src is an image instance, rendering will not be triggered by default
```typescript
const img = new Image();
const image = new GImage({
src: img
});
img.src = 'xxx';
```
The reason for this problem is that when passing an image instance, the `complete` property of the image is checked asynchronously to see if it is true, but by default re-rendering is triggered by asynchronous callback only when src is a string.
Therefore, regardless of the type of src, re-rendering should be triggered by asynchronous callback to ensure that the image is correctly rendered after loading successfully.
| 🇺🇸 English | fix: when image src is an image instance, rendering will not be triggered by default |
| 🇨🇳 Chinese | fix: 当 image 元素的 src …
> fix: when image src is an image instance, rendering will not be triggered by default

- packages/g-plugin-device-renderer/src/render/RenderCache.ts
Fix https://github.com/antvis/G/issues/1826
修复RenderPipeline无法被缓存的问题
配合上游的[几个PR](https://github.com/antvis/g-device-api/pulls)，现在WebGPU的几个DEMO可以正常跑了
> fix: fixed the issue where RenderCache could not cache RenderPipeline

- .changeset/purple-adults-march.md
- __tests__/demos/bugfix/group-with-stroke.ts
- __tests__/demos/bugfix/index.ts
- __tests__/unit/abstract-renderer.spec.ts
- __tests__/unit/display-objects/display-object.node.spec.ts
- packages/g-lite/src/css/StyleValueRegistry.ts
- packages/g-lite/src/display-objects/Group.ts
> 基于 `PARSED_STYLE_LIST` 属性列表进行样式处理，需要设置 `enableMassiveParsedStyleAssignOptimization` 为 `true`
修复前（绿色为包围盒区域）：
修复后：
> fix: fix incorrect bounds calculate when pass stroke and lineWidth to group

- .changeset/empty-falcons-occur.md
- __tests__/main.ts
- packages/g-lite/src/Canvas.ts
> cleanUp 为 true 时正常执行 Canvas 及下面各元素的销毁生命周期
> cleanUp 为 false 时，跳过上述逻辑，但不会影响相关内存释放
> refactor: adjust destroy clean-up logic

- .changeset/wicked-rabbits-exist.md
- __tests__/demos/bugfix/group-with-stroke.ts
- packages/g-lite/src/display-objects/CustomElement.ts
- packages/g-lite/src/display-objects/Fragment.ts
> 与 https://github.com/antvis/G/pull/1847 中 Group 问题相同
> fix: fix custom element with stroke may cause bounds error

- .changeset/tidy-bulldogs-give.md
- __tests__/demos/bugfix/index.ts
- __tests__/demos/bugfix/switch-renderer.ts
- __tests__/main.ts
- __tests__/unit/abstract-renderer.spec.ts
- packages/g-lite/src/Canvas.ts
问题原因：destroy 时 将 `context.renderingContext.root` 置为 `null`，导致 `setRenderer` 中调用 `context.contextService.init()` 时找不到 `root` 对象
> fix: fix error occurred when setRenderer

- packages/g-lite/src/css/StyleValueRegistry.ts
- packages/g-lite/src/css/parser/dimension.ts
修复path/line style lineDash不支持多位数组
https://github.com/antvis/G/issues/1866
> fix: lineDash支持多位数组

- .changeset/two-pumpkins-add.md
- packages/g-lite/src/services/TextService.ts
see https://github.com/antvis/S2/issues/3040
If the first character is a line break, the first line of text is null, resulting in an error in getting the character length. We can just check this boundary condition.
| 🇺🇸 English | fix: rendering error when line break appears at the beginning of text |
| 🇨🇳 Chinese | fix: 文本首字符为换行符时渲染异常 |
> fix: rendering error when line break appears at the beginning of text

- .changeset/honest-keys-train.md
- __tests__/demos/bugfix/1677.ts
- __tests__/demos/event/dblClick.ts
- __tests__/demos/perf/event.ts
- packages/g-canvas/src/Canvas2DContextService.ts
- packages/g-canvaskit/src/CanvasKitContextService.ts
- packages/g-image-exporter/src/ImageExporter.ts
- packages/g-lite/src/Canvas.ts
- packages/g-lite/src/dom/Node.ts
- packages/g-lite/src/dom/interfaces.ts
- packages/g-lite/src/services/EventService.ts
- packages/g-lite/src/types.ts
- packages/g-lite/src/utils/raf.ts
- packages/g-mobile-svg/src/SVGContextService.ts
- packages/g-plugin-device-renderer/src/TexturePool.ts
- packages/g-plugin-image-loader/src/ImagePool.ts
- packages/g-plugin-svg-renderer/src/shapes/defs/Pattern.ts
- packages/g-svg/src/SVGContextService.ts
- packages/g-webgl/src/WebGLContextService.ts
- packages/g-webgpu/src/WebGPUContextService.ts
- site/docs/api/canvas/options.en.md
- site/docs/api/canvas/options.zh.md
There are a lot of direct references to `window` in the global code, which is strongly coupled with the web platform, and the calculation of `dpr` is repeated in each renderer. It is easy to maintain by converging it into the core package.
| 🇺🇸 English | refactor: reduce global redundant code |
| 🇨🇳 Chinese | refactor: 减少全局冗余代码 |
> refactor: reduce global redundant code

- .changeset/long-clouds-yawn.md
- packages/g-lite/src/utils/path.ts
fixed #1844
When `markerStartOffset`/`markerEndOffset` are set for the path element, the processing of the `A` command differs between canvas and svg. svg directly offsets the last two parameters of the `A` command, while canvas appends an `L` command. 
Considering the complexity of the `A` command, the logic of svg is kept consistent with canvas
to ensure that existing products that rely on this feature work properly.
> https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/d#elliptical_arc_curve
| 🇺🇸 English | fix: svg path element A command drawing abnormality |
| 🇨🇳 Chinese | fix: svg path 元素的 A 命令绘制异常 |
> fix: svg path element A command drawing abnormality

- .changeset/silver-tigers-roll.md
- __tests__/demos/bugfix/textWordWrap.ts
- __tests__/demos/event/hierarchy.ts
- packages/g-lite/src/services/TextService.ts
#1833 
Measuring text is an expensive operation, so G internally calculates the overall text width on a character-by-character basis and caches it when calculating line breaks. Due to the complexity of text rendering, this results in a larger result than measuring the entire text at once, resulting in less precise line break locations.
However, we cannot simply adjust the character-by-character strategy to measure the entire text, which will cause serious performance problems in scenarios with a long text.
> <img width="980" alt="image" src="https://github.com/user-attachments/assets/ee5d1021-1830-4f0e-a27b-ca460e5b3975" />
> In the case of long text, the performance difference between the two different strategies is two orders of magnitude
On the other hand, we can combine the two …
> fix: the text wrapping position is not accurate

- .changeset/ten-impalas-type.md
- packages/g-lite/src/services/TextService.ts
#1876 
#1876 
| 🇺🇸 English | fix: text wrapping boundary cases |
| 🇨🇳 Chinese | fix: 文本换行边界条件 |
> fix: text wrapping boundary cases

- .changeset/sour-hornets-turn.md
- __tests__/demos/bugfix/textWordWrap.ts
- packages/g-lite/src/services/TextService.ts
#1833 
see #1876 
When correcting the calculation of line break positions, line breaks were not taken into account, resulting in abnormal display when line breaks existed in the final rendered text.
Before
After
| 🇺🇸 English | fix: line break position does not take into account newline characters |
| 🇨🇳 Chinese | fix: 换行位置计算未考虑换行符 |
> fix: line break position does not take into account newline characters

- .changeset/popular-items-wave.md
- __tests__/demos/bugfix/textWordWrap.ts
- packages/g-lite/src/services/TextService.ts
#1833 
see #1876 
When calculating the line break position, a more accurate result is obtained by adopting a strategy of character-by-character measurement cache combined with whole-text measurement. Among them, when the whole-text measurement strategy is used to approximate the optimal value character by character near the threshold, it is not considered that when a single character cannot be displayed, the character-by-character correction will cause the starting character position of each line to return to the beginning of the whole text, resulting in abnormal display after multiple lines of text are wrapped.
In order to deal with this edge case, the index of the last character of each line should be recorded, and when calculating the line break position of the current line, the …
> fix: multi-line text wrapping exception

- .changeset/config.json
- .changeset/ten-toes-whisper.md
- __tests__/demos/bugfix/textWordWrap.ts
- packages/g-lite/src/services/TextService.ts
fixed #1897 
When processing text line breaks, in the initial implementation of measuring text width character by character, the line width will be directly obtained from the cache when encountering a word break, because each character is already in the cache; in the improved line break strategy, the width of the entire line of text will be measured near the line break threshold to determine the final more accurate line break character position, which means that the width of each single character may not be in the cache, which causes the exception to be thrown
This can be done by changing the word break judgment of the text to real-time measurement to obtain the line width. (This will not cause a serious performance reduction, because we use the existing cache) …
> fix: abnormal word breaking in text

- site/.dumirc.ts
> docs: official document navigation exception

- .changeset/pretty-crews-itch.md
- __tests__/demos/bugfix/1176.ts
- __tests__/demos/bugfix/1882.ts
- __tests__/demos/bugfix/index.ts
- packages/g-web-components/src/shape/HTML.ts
- site/examples/ecosystem/declarative/demo/web-components-react.tsx
- site/examples/ecosystem/declarative/demo/web-components.js
#1882 
see #1882 , since the G engine has abandoned support for numerical units in element attribute values, the official documentation examples need to be updated to ensure normal rendering.
On the other hand, the `g-html` element cannot be rendered on the first screen because the rendering logic only occurs when the attributes are updated. By default, triggering a rendering once can solve the problem.
| 🇺🇸 English | fix: web-components element rendering exception |
| 🇨🇳 Chinese | fix: web-components 元素渲染异常 |
> fix: web-components element rendering exception

- .changeset/loud-icons-press.md
- .eslintrc.cjs
- __tests__/demos/bugfix/1906.ts
- __tests__/demos/bugfix/index.ts
- packages/g-plugin-canvas-renderer/src/shapes/styles/Image.ts
- packages/g-plugin-image-loader/src/ImagePool.ts
When the `enableLargeImageOptimization` configuration item is turned on, the rendering of large-size images will no longer be synchronous, and slices and downsampled image data will be generated asynchronously before triggering rendering. During this asynchronous slicing process, if the element object has been removed from the DOM tree, an error will be reported.
```ts
object.ownerDocument.defaultView.context.renderingService.dirtify();
```
At this time, `object.ownerDocument=null`.
Considering the edge cases, after the image data is asynchronously prepared, it is necessary to determine whether the Image object instance has been removed from the DOM tree before executing the subsequent logic.
| 🇺🇸 English | fix: image element rendering …
> fix: image element rendering triggers an exception

- packages/g-plugin-a11y/src/AriaManager.ts
https://github.com/antvis/S2/issues/3124
> fix: add pointerEvents none

- .changeset/sour-dogs-fly.md
- __tests__/demos/bugfix/1910.ts
- __tests__/demos/bugfix/index.ts
- packages/g-lite/src/services/RenderingService.ts
- packages/g-lite/src/services/SceneGraphService.ts
- packages/g-plugin-canvas-renderer/src/CanvasRendererPlugin.ts
- packages/g-plugin-canvaskit-renderer/src/CanvaskitRendererPlugin.ts
fixed #1910 
In the rendering process, in order to ensure the correct rendering order of child elements, we need to check whether there are child elements with `z-index != 0`. If so, we first sort them and save them to the `sorted` list for rendering. If not, we will directly render them in the `childNodes` list (that is, the order in which the elements are mounted).
There are 3 problems here:
1. In each frame rendering process, by updating the `z-index` of the element, if a parent element no longer has a child element with `z-index != 0`, the rendering list will be abnormal
To solve this problem, it is necessary to determine whether there is a child element with `z-index != 0` after the child elements are sorted. If not, we will clear the `sorted` list to obtain the correct rendering …
> fix: element z-index sorting rendering abnormality

- __tests__/demos/bugfix/1910.ts
- packages/g-lite/src/services/RenderingService.ts
fixed #1910 
In #1921 , we fixed the rendering anomaly in 3 scenarios, but missed a typical case in an interactive scenario. If we do not have an element with `zIndex != 0` in the child element during the update process, we will clear the `sorted` list. However, if a new child element with `zIndex != 0` is mounted later, it is not enough to just check whether the `sorted` list exists. We should check whether the `sorted` list is empty. If it is empty, we will directly sort all child elements to get the correct rendering list.
| 🇺🇸 English | fix: rendering anomalies caused by element zIndex update |
| 🇨🇳 Chinese | fix: 元素 zIndex 更新导致的渲染异常 |
> fix: rendering anomalies caused by element zIndex update

- packages/g-web-animations-api/src/dom/Animation.ts
https://github.com/antvis/S2/issues/3092
在单元格绘制G2 Chart的场景下，横向滚动时会不断地创建新的单元格，销毁旧的单元格。创建单元格后G2的Chart会产生动画，但销毁太快导致动画还没执行单元格Chart已经destroy了。因为@antv/component的Navigator.goto会等待动画finished.then后执行Callback，finished函数会将动画放到G的packages/g-web-animations-api/src/dom/AnimationTimeline.ts的animationsWithPromises数组中等待执行，而动画target已经destroy了，根本得不到执行，导致越攒越多，导致内存泄漏。可以看到下面animationsWithPromises中持有的1597个动画对象，其动画目标元素都已经destroy了，没有必要再持有。
| 🇺🇸 English |     Discard animation when target is destroyed      |
| 🇨🇳 Chinese |    在动画目标已经被销毁的情况下，直接丢弃动画，避免内存泄露       |
> perf: discard animation when target is destroyed to avoid memory leaks 

- .changeset/all-dots-check.md
- __tests__/demos/2d/transform.ts
- __tests__/unit/css/properties/transform.spec.ts
- packages/g-lite/src/utils/transform-mat4.ts
fixed #1953 
see https://github.com/antvis/G/issues/1953#issuecomment-3088998453
To ensure that the matrix is always reversible, the determinant must not be `0`, and the diagonal component of the matrix, namely `scale`, must also not be `0`. Therefore, we can set a minimum threshold. When the scale is small enough, the visual element will be invisible and will not affect the existing product visual effects. It may affect the test snapshot, so just update the test benchmark.
| 🇺🇸 English | fix: prevent NaN in transform calculations when scale is 0 |
| 🇨🇳 Chinese | fix: 当 scale 为 0 时，防止在变换计算中出现 NaN |
> fix: prevent NaN in transform calculations when scale is 0

- packages/g-lite/src/services/SceneGraphService.ts
s2滚动场景下，有大量嵌套的节点会走到dirtyToRoot。排在前面的元素自下而上dirty后，排在后面的元素不需要再给父元素dirty了。
| before   | After |
|  <img width="1022" height="58" alt="image" src="https://github.com/user-attachments/assets/192c8abd-4dc7-4ce1-8701-025c8a78c056" />  |  <img width="1080" height="66" alt="image" src="https://github.com/user-attachments/assets/dbb61e30-f6bf-41f8-bd60-ebaa0949b0b0" />  |
| 🇺🇸 English |    Avoid duplicate dirty parent elements to improve performance by 2%       |
| 🇨🇳 Chinese |     避免重复dirty父级元素提升2%性能      |
> perf: Avoid duplicate dirty parent elements to improve performance by 2%
